# %%
EF, FC_ = 'production efficiency', 'financial condition'
_emp = WEMP[BCODES].combine_first(EMP_DSK[BCODES])
mrow(EF, 'Əmək məhsuldarlığı (buraxılış/işçi)', 'Labour productivity, real output per employee', 'Q_b / employees', 'thsd AZN 2015 prices', 'DSK; workbook', 'industry 010, 009, 006; industry sheets (headcount)', 'branch', 'annual', _emp, 'available now', DL + '; ' + WB_, 'efficiency ranking, quadrant, forecast path', 'ranking table; quadrant; fan', 'annual')
mrow(EF, 'Əmək məhsuldarlığı (ƏD/işçi)', 'Labour productivity, real value added per employee', 'VA_b / P_b / employees', 'thsd AZN 2015 prices', 'DSK', 'national accounts 015_2; 006', 'branch', 'annual', _emp.loc[2016:], 'available now', DL, 'efficiency ranking', 'ranking table', 'annual')
mrow(EF, 'Əmək məhsuldarlığı (rəsmi)', 'Labour productivity by section (official)', 'VA / employed', 'AZN', 'DSK', 'national accounts 030_2', 'section', 'annual', '2017-2025', 'available now', DL, 'cross-check', 'KPI card', 'annual')
mrow(EF, 'Aralıq istehlakın payı', 'Intermediate-consumption share of output', 'IC / GO', '%', 'DSK', 'national accounts 015, 015_1', 'branch', 'annual', NA_IC, 'available now', DL, 'TFP materials share; cost structure', 'time series', 'annual')
mrow(EF, 'Kapital məhsuldarlığı', 'Capital productivity', 'Q_b / K_b (perpetual inventory)', 'ratio', 'DSK', 'industry 019; national accounts 031', 'branch / section', 'annual', K, 'available now (derived)', DL, 'efficiency, TFP capital input', 'time series', 'annual')
mrow(EF, 'Ümumi amil məhsuldarlığı (TFP)', 'TFP growth, gross output (branches) and value added (sections)', 'Tornqvist residual with observed cost shares', 'log points', 'DSK; FR1; FR4', 'NA 013, 015, 015_1, 031; industry 019; FR4 hired', 'branch, section', 'annual', TFP.dlnTFP.unstack(0), 'available now (derived)', DL, 'efficiency decomposition (Part 7.2)', 'waterfall / decomposition chart', 'annual')
mrow(EF, 'Əmək haqqı - məhsuldarlıq fərqi', 'Wage-productivity gap', 'dln(w/P) - dln LP', 'log points', 'DSK; workbook', 'industry 006_2; industry sheets', 'branch', 'annual', WAGEC, 'available now', DL, 'unit-labour-cost pressure', 'bar chart', 'annual')
mrow(EF, 'İnnovasiya intensivliyi', 'Innovation intensity', 'innovation expenditure / output', '%', 'DSK', 'industry 020_3 (also 020_1, 020_2, 020_4, 020_5)', 'branch', 'annual', INNOV, 'available now', DL, 'efficiency profile', 'ranking table', 'annual')
mrow(EF, 'İnvestisiya norması', 'Investment rate (renewal proxy)', 'I / GO', '%', 'DSK', 'industry 019, 010', 'branch', 'annual', INV, 'available now', DL, 'determinants panel; early-warning flag', 'heat map', 'annual')
mrow(EF, 'Əsas fondların yenilənmə, çıxma, köhnəlmə dərəcəsi', 'Fixed-asset renewal, disposal and depreciation rates', 'published rates', '%', 'DSK', 'industry 017_2-017_7 (no longer published, F1)', 'branch', 'annual', 'none', 'not available', 'request to DSK to resume publication', 'renewal flag', 'heat map', 'annual', 'investment rate (DSK 019/010); consumption of fixed capital / VA by section (NA 013, 025)')
mrow(EF, 'Kapital qoyuluşlarının səmərəlilik indeksi', 'Capital-yield index', 'published index', 'index', 'DSK', 'industry 018_1 (old numbering, discontinued)', 'branch', 'annual', 'none', 'not available', 'request to DSK', 'efficiency', 'time series', 'annual', 'capital productivity from perpetual inventory')
mrow(EF, 'Enerji intensivliyi', 'Energy intensity of production', 'energy cost / output', '%', 'DSK; Azerenerji', 'not published by branch (SME electricity costs only, entrepreneurship 037, 2023-2024)', 'branch', 'annual', 'none', 'not available', DSA, 'cost structure, determinants', 'ranking table', 'annual', 'SME electricity and fuel costs (entrepreneurship 035, 037)')
mrow(FC_, 'Ümumi əməliyyat mənfəəti (bölmələr)', 'Gross operating surplus margin by section', 'GOS / VA; GOS / GO', '%', 'DSK', 'national accounts 013', 'section (B, C, D, E)', 'annual', INC.GOS.unstack(0), 'available now', DL, 'financial-condition forecast (Part 14)', 'time series with fan', 'annual')
mrow(FC_, 'Əmək haqqının ƏD-də payı', 'Labour share of value added', 'compensation / VA', '%', 'DSK', 'national accounts 013, 023', 'section', 'annual', INC.CE.unstack(0), 'available now', DL, 'margin decomposition', 'time series', 'annual')
mrow(FC_, 'Əsas kapitalın istehlakı', 'Consumption of fixed capital / VA', 'CFC / VA', '%', 'DSK', 'national accounts 013, 025', 'section', 'annual', INC.CFC.unstack(0), 'available now', DL, 'renewal proxy, net margin', 'time series', 'annual')
mrow(FC_, 'Sahə üzrə mənfəət proksisi', 'GOS-proxy margin by manufacturing branch', '(VA - gross wage bill) / GO', '%', 'DSK; workbook', 'NA 015, 015_2; industry 006, 006_2; industry sheets', 'branch', 'annual', GOSP, 'available now (derived)', DL + '; ' + WB_, 'quadrant, early warning, forecast', 'quadrant; ranking; fan', 'annual')
mrow(FC_, 'Mənfəət vergisi bəyannamələri: xalis marja', 'Profit-tax declarations: net margin', '(income after deductions - deductible expenses) / deductible expenses', '%', 'DVX', "workbook 'DVX üzrə göstəricilər' r215-r222", 'all payers', 'annual', DVX.pt_income, 'available now', WB_, 'economy-wide profitability KPI', 'KPI card', 'annual', 'branch breakdown requested from DVX')
mrow(FC_, 'Bəyan edilmiş zərər', 'Declared losses', 'loss / taxable profit', '%', 'DVX', 'DVX r221', 'all payers', 'annual', DVX.pt_loss, 'available now', WB_, 'distress KPI', 'KPI card', 'annual')
mrow(FC_, 'Effektiv mənfəət vergisi nisbəti', 'Effective profit-tax ratio (DVX "rentabellik", F7)', 'payable tax / income after deductions', '%', 'DVX', 'DVX r223', 'all payers', 'annual', DVX.pt_rent, 'available now', WB_, 'tax burden', 'KPI card', 'annual')
mrow(FC_, 'Gəlir vergisi bəyannamələri (fərdi sahibkarlar)', 'Income-tax declarations of individual entrepreneurs', 'profit / income; loss', '%', 'DVX', 'DVX r224-r232', 'all payers', 'annual', DVX.it_income, 'available now', WB_, 'small-business profitability', 'KPI card', 'annual')
mrow(FC_, 'Vergi borcları', 'Tax arrears', 'stock', 'mn AZN', 'DVX', 'DVX r43', 'national', 'annual', DVX.arrears, 'available now', WB_, 'early-warning context', 'KPI card', 'monthly')
mrow(FC_, 'Sənaye dövriyyəsi (vergi bazası)', 'Industry turnover on the tax basis', 'turnover', 'mn AZN', 'DVX', 'DVX r53-r57', 'industry / non-oil industry', 'annual', DVX.turn_ind, 'available now', WB_, 'cross-check of output', 'time series', 'annual')
mrow(FC_, 'İnvestisiyanın öz vəsaitləri hesabına maliyyələşməsi', 'Investment self-financing share', 'own funds / total investment', '%', 'DSK via workbook', "workbook 'Real sektor' r114 / r80", 'national', 'annual', SELF_FIN, 'available now (3 years annual)', WB_, 'financial capacity KPI', 'KPI card', 'annual')
mrow(FC_, 'Hazır məhsul ehtiyatları', 'Finished-goods stocks to output', 'stocks / GO', '%', 'DSK', 'industry 013', 'branch', 'annual', STK, 'available now', DL, 'early-warning flag (rising stocks)', 'heat map', 'annual')
mrow(FC_, 'KOB-ların aktivləri, ehtiyatları, vergiləri', 'SME assets, stocks and taxes paid', 'levels', 'mn AZN', 'DSK', 'entrepreneurship 039, 040, 041', 'section x size', 'annual', '2023-2024', 'available now (2 years)', DL, 'SME balance-sheet profile', 'table', 'annual')
for az, en, f_ in [('Likvidlik əmsalları', 'Liquidity: current, quick, cash ratios', 'CA/STL; (CA-inv)/STL; cash/STL'),
                   ('Borc yükü, faiz örtüyü', 'Leverage and interest cover', '(STL+LTL)/E; EBIT/interest'),
                   ('Rentabellik (DuPont)', 'Profitability: ROE (DuPont), ROA, EBIT margin', 'NP/Rev x Rev/TA x TA/E'),
                   ('Dövriyyə göstəriciləri', 'Turnover: assets, inventories, receivable days', 'Rev/TA; COGS/inv; rec/Rev x 365'),
                   ("Altman Z''-EM", "Distress score (Altman Z''-EM, literature coefficients)", "3.25 + 6.56 X1 + 3.26 X2 + 6.72 X3 + 1.05 X4")]:
    mrow(FC_, az, en, f_, 'ratio', 'DVX', 'enterprise balance sheet and P&L panel (requested 24.08.2026)', 'firm', 'annual', 'none', 'requested', DSA,
         'Layer B engine (Part 17)', 'firm scorecard; peer percentile; early-warning list', 'annual', 'none for firms; aggregate proxies above')
mrow(EF, 'Müəssisə məşğulluğu və əmək haqqı fondu', 'Firm employment and wage bill', 'persons; wage bill', 'persons; thsd AZN', 'DSMF', 'contributor records (requested)', 'firm', 'monthly', 'none', 'requested', DSA, 'Layer B productivity, TFP', 'firm scorecard', 'monthly', 'branch headcount (DSK 006, workbook)')
mrow(FC_, 'Sahələr üzrə kredit, problemli kreditlər', 'Credit and NPLs by branch', 'loans; NPL / loans', 'mn AZN; %', 'CBAR', 'not in project (FR1 holds total industry credit)', 'branch', 'monthly', 'none', 'not available', DSA + ' with CBAR', 'financial-condition driver', 'time series', 'monthly', 'FR1 industry credit (cred_ind_n) at section level')
SRC_MATRIX = pd.DataFrame(MX)
SRC_MATRIX.index = [f'I{i+1:02d}' for i in range(len(SRC_MATRIX))]
SRC_MATRIX['status_group'] = SRC_MATRIX.status.str.extract(r'^(available now|requested|not available)')[0]
print(SRC_MATRIX.status_group.value_counts().to_string())
display(SRC_MATRIX[['pillar', 'indicator_en', 'source_institution', 'dataset_table_row', 'years_available_now', 'status', 'presentation_form']])
