"""b_labels.py — Azerbaijani column labels: panel/i18n/columns_az.csv → js/labels.js (U.COLS), and the check that every
column of every bundled table has a label (table headers are user-facing)."""
import csv
import json

from . import bcore as C

SRC = C.PANEL / "i18n" / "columns_az.csv"


def build():
    with SRC.open(encoding="utf-8") as fh:
        L = {r["key"]: r["az"] for r in csv.DictReader(fh) if r["key"]}
    js = ("/* labels.js — generated by build_panel.py from panel/i18n/columns_az.csv — do not edit */\n"
          "(function () { 'use strict'; window.U.COLS = " + json.dumps(L, ensure_ascii=False, sort_keys=True, indent=0) + "; })();\n")
    (C.PANEL / "js" / "labels.js").write_text(js, encoding="utf-8")
    return L


def _tables(o, where, out):
    if isinstance(o, dict):
        if "c" in o and "r" in o:
            out.append((where, o["c"]))
            return
        for k, v in o.items():
            _tables(v, f"{where}.{k}", out)


def check(L):
    """Missing label → warning (the panel shows the column code with spaces); an error only when that fallback would
    show English words — so a module adding an Azerbaijani-named column does not break the build."""
    from .b_i18n import bad_words
    errs, seen, warns = [], set(), []
    for name, (var, obj) in sorted(C.BUNDLES.items()):
        tabs = []
        _tables(obj, name, tabs)
        for where, cols in tabs:
            for c in cols:
                if c not in L and c not in seen:
                    seen.add(c)
                    msg = f"{where}: sütun etiketi yoxdur: {c} (panel/i18n/columns_az.csv)"
                    (errs if bad_words(c.replace("_", " ")) else warns).append(msg)
    for w in warns:
        print("  xəbərdarlıq —", w)
    return errs
