"""pybundle — builds the in-browser Python bundle of a panel (identical copy in the three units' panel/_build/).

    from _build import pybundle; info = pybundle.build(PANEL, "micro_web")

1. `webcore.py record` (native subprocess) runs the web module's SAMPLES and stores the results of its REPLAY functions;
2. `webcore.py trace` re-runs SAMPLES with those replayed, under an audit hook → every project file and module used;
3. a deterministic zip (sorted entries, fixed timestamps) of those files + INCLUDE globs + panel/py/*.py + _replay.pkl,
   laid out as in the project (MicroUnit/…, RiskUnit/…) → panel/py/<unit>_bundle.zip, and panel/py/bundle.js
   (window.PYB: file, md5, size, Pyodide version, packages, routes).
Failure never breaks the panel build: the previous bundle is kept and a warning returned (the panel then offers
server or bundled results only)."""
import hashlib, json, os, subprocess, sys, tempfile, zipfile
from pathlib import Path

PYODIDE = "0.29.3"
CDN = "https://cdn.jsdelivr.net/pyodide/v%s/full/" % PYODIDE
SKIP_SUFFIX = (".db", ".db-wal", ".db-shm", ".log", ".pyc", ".lock")
ZDATE = (1980, 1, 1, 0, 0, 0)


def _run(args, cwd, log):
    env = dict(os.environ, PYTHONDONTWRITEBYTECODE="1", MICRO_NO_NETWORK="1", RISK_NO_NETWORK="1", POLICY_NO_NETWORK="1",
               PYTHONHASHSEED="0")
    r = subprocess.run([sys.executable] + args, cwd=cwd, env=env, capture_output=True, text=True, timeout=900)
    if r.returncode:
        raise RuntimeError((r.stderr or r.stdout)[-1500:])
    return r


def collect(project, tr, pydir):
    meta = tr["meta"]
    files = set(tr["files"]) | set(tr["py"])
    for pat in meta.get("INCLUDE") or []:
        files |= {str(p.relative_to(project)) for p in project.glob(pat) if p.is_file()}
    files |= {str(p.relative_to(project)) for p in pydir.glob("*.py")}
    out = []
    for f in sorted(files):
        if f.endswith(SKIP_SUFFIX) or "__pycache__" in f or f.startswith("..") or "/panel/py/" in f and f.endswith(".zip"):
            continue
        if (project / f).is_file():
            out.append(f)
    return out


def write_zip(project, files, extra, out):
    tmp = out.with_suffix(".tmp")
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as z:
        items = [(f, (project / f).read_bytes()) for f in files] + sorted(extra.items())
        for name, data in sorted(items):
            zi = zipfile.ZipInfo(name, ZDATE)
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = 0o644 << 16
            z.writestr(zi, data, compresslevel=9)
    tmp.replace(out)


def build(panel, entry, log=print):
    """-> {"ok", "zip", "bytes", "md5", "files", "raw_bytes", "warning"?}"""
    panel = Path(panel).resolve()
    pydir, unit_dir = panel / "py", panel.parent
    project = unit_dir.parent
    zname = "%s_bundle.zip" % unit_dir.name.lower()
    out = pydir / zname
    try:
        with tempfile.TemporaryDirectory() as td:
            rp, tp = Path(td) / "replay.pkl", Path(td) / "trace.json"
            _run(["webcore.py", "record", entry, str(rp)], pydir, log)
            _run(["webcore.py", "trace", entry, str(rp), str(tp)], pydir, log)
            tr = json.loads(tp.read_text(encoding="utf-8"))
            bad = [r for r in tr["responses"] if r["status"] != 200]
            if bad:
                raise RuntimeError("nümunə sorğu uğursuz: %s %s → %s %s" % (bad[0]["method"], bad[0]["path"], bad[0]["status"],
                                                                          json.dumps(bad[0]["body"], ensure_ascii=False)[:400]))
            files = collect(project, tr, pydir)
            rel_py = str((pydir / "_replay.pkl").relative_to(project))
            write_zip(project, files, {rel_py: rp.read_bytes()}, out)
            meta = tr["meta"]
            raw = sum((project / f).stat().st_size for f in files) + rp.stat().st_size
    except Exception as e:  # noqa: BLE001
        msg = "brauzer paketi qurulmadı (%s: %s)%s" % (type(e).__name__, str(e)[-600:],
                                                     " — əvvəlki paket saxlanıldı" if out.exists() else "")
        if not (pydir / "bundle.js").exists():
            (pydir / "bundle.js").write_text("/* generated by build_panel.py — no in-browser bundle */\nwindow.PYB=null;\n", encoding="utf-8")
        return {"ok": False, "warning": msg}
    data = out.read_bytes()
    md5 = hashlib.md5(data).hexdigest()
    pyb = {"unit": meta["UNIT"], "zip": "py/" + zname, "md5": md5, "bytes": len(data), "raw_bytes": raw, "files": len(files) + 1,
           "pyodide": PYODIDE, "cdn": CDN, "packages": meta["PACKAGES"], "entry": meta["ENTRY"], "routes": meta["ROUTES"],
           "root": "/mp", "pypath": str(pydir.relative_to(project)), "notes": meta.get("NOTES") or []}
    js = ("/* generated by build_panel.py (panel/_build/pybundle.py) — in-browser Python bundle, do not edit */\n"
          "window.PYB=" + json.dumps(pyb, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + ";\n")
    (pydir / "bundle.js").write_text(js, encoding="utf-8")
    return {"ok": True, "zip": str(out), "bytes": len(data), "md5": md5, "files": len(files) + 1, "raw_bytes": raw,
            "samples": [(r["path"], r["native_s"]) for r in tr["responses"]]}


def report(info):
    if not info["ok"]:
        return "BRAUZER PAKETİ: XƏBƏRDARLIQ — " + info["warning"]
    return "BRAUZER PAKETİ OK — %s: %d fayl, %.1f MB (sıxılmamış %.1f MB), md5 %s; nümunələr: %s" % (
        Path(info["zip"]).name, info["files"], info["bytes"] / 1e6, info["raw_bytes"] / 1e6, info["md5"][:10],
        ", ".join("%s %.1f s" % s for s in info["samples"]))
