"""NFR2 — automatic update of risk scores when new data arrives (acceptance: ≤ 24 hours).

    python3 update.py --daily         # fast (≈1–2 min): global + Azerbaijan feeds → upstream store (if a unit published
                                      #   a new vintage) → consensus → daily forecast-impact monitor (D2, D4–D7)
    python3 update.py --full          # everything: --daily + the full scoring pipeline (run_all) and reports
    python3 update.py                 # v1 cycle: fetch feeds, recompute the scoring pipeline if any input changed
    python3 update.py --no-fetch      # only check local inputs (registers, upstream model outputs)
    python3 update.py --force         # recompute even if nothing changed
    python3 update.py --watch 15      # stay running; check every 15 minutes (manual register edits)
    python3 update.py --daily --backfill 400   # also back-fill up to 400 CBAR bulletins in this run

Every input is fingerprinted: the latest vintage of each live feed, every upstream file of the §15.5.1 macro model,
the §15.5.2 micro unit and the Ministry unit, and every Ministry-editable file in input/. When the fingerprint changes
the full scoring pipeline runs and output/NFR2_update_log.csv records when the change was first seen, when the scores
were rewritten and the lag in hours. The schedule in scheduler/ (generated by scheduler/install.py with paths derived
from this folder) runs --full every morning and --daily twice more during the day, so the lag stays far inside 24 hours.
A cycle that fails is logged and alerts on the next successful run; it never leaves half-written scores.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
import time
import traceback
from datetime import datetime, timezone

import pandas as pd

from riskunit import config, feeds

STATE = config.OUTPUT / "NFR2_state.json"
LOG = config.OUTPUT / "NFR2_update_log.csv"
LOG_COLS = ["basladi_utc", "bitdi_utc", "tetik", "deyisen_girisler", "ilk_goruldu_utc", "muddet_san", "sla_saat",
            "sla_odenilir", "yuksek_prioritet", "xeberdarliq_sayi", "baseline_id", "status"]


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha(p) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def fingerprint() -> dict[str, str]:
    fp = {}
    man = feeds.read_manifest()
    for r in man[man.status == "ok"].groupby("feed").tail(1).itertuples():
        fp[f"axın:{r.feed}"] = r.sha256
    for key, p in {**config.MACRO_FILES, **config.MICRO_FILES, **config.MACRO_FILES_V2, **config.MICRO_FILES_V2,
                   **config.MINISTRY_FILES}.items():
        if p.exists():
            fp[f"model:{key}"] = _sha(p)
    for p in sorted(config.INPUT.glob("*.csv")):
        fp[f"giriş:{p.name}"] = _sha(p)
    return fp


def load_state() -> dict:
    return json.loads(STATE.read_text()) if STATE.exists() else {"fingerprint": {}, "pending_since": {}}


def append_log(row: dict) -> None:
    new = pd.DataFrame([row], columns=LOG_COLS)
    if LOG.exists():
        new = pd.concat([pd.read_csv(LOG), new], ignore_index=True)
    new.to_csv(LOG, index=False)


def stage_note(stages) -> tuple[str, str]:
    """('xəta'|'xəbərdarlıq'|'ok', text) from run_all stage rows (v2.4: feed failures are no longer hidden)."""
    import run_all
    err = [r["stage"] for r in stages or [] if run_all.level_of(r["status"]) == "xəta"]
    warn = [r["stage"] for r in stages or [] if run_all.level_of(r["status"]) == "xəbərdarlıq"]
    if err:
        return "xəta", "mərhələ xətası: " + ", ".join(err) + (f"; xəbərdarlıq: {', '.join(warn)}" if warn else "")
    return ("xəbərdarlıq", "xəbərdarlıq: " + ", ".join(warn)) if warn else ("ok", "")


def with_stages(status: str, stages) -> str:
    lvl, txt = stage_note(stages)
    if lvl == "ok":
        return status
    return f"qismən: {txt}" if (lvl == "xəta" and status == "uğurlu") else f"{status} ({txt})"


def cycle(fetch: bool = True, force: bool = False, verbose: bool = True) -> dict:
    started = now()
    import run_all
    pre = None
    if fetch:                                     # all feeds (global + AZ) and the D1–D7 data stages, before fingerprinting
        R0 = run_all.Runner(verbose)
        pre = run_all.data_stages(R0, fetch=True, verbose=verbose)
        pre["stages"] = R0.rows
    st = load_state()
    fp = fingerprint()
    changed = sorted(k for k in fp if st["fingerprint"].get(k) != fp[k])
    # a change stays "pending" (with its first-seen time) until a recompute succeeds
    pending = st.get("pending_since", {})
    for k in changed:
        pending.setdefault(k, started)
    if not pending and not force:
        if verbose:
            print("Dəyişiklik yoxdur — skorlar aktualdır.")
        return {"status": with_stages("dəyişiklik yoxdur", (pre or {}).get("stages"))}
    first_seen = min(pending.values()) if pending else started
    trig = "məcburi" if force and not pending else "yeni məlumat"
    t0 = time.time()
    row = {"basladi_utc": started, "tetik": trig, "deyisen_girisler": ";".join(sorted(pending)) or "—",
           "ilk_goruldu_utc": first_seen}
    try:
        from riskunit import factors, spine
        spine.clear_caches()
        factors.clear_caches()
        c = run_all.build_context(verbose=verbose, data=pre is None)
        if pre is not None:
            c["data"] = pre
            c["stages"] = pre["stages"] + c["stages"]
        from riskunit import docs, report
        report.build_all(c, pdf=True)
        docs.update_methodology(c)
        c["elapsed"] = time.time() - t0
        run_all.write_summary(c, "update.py (NFR2 dövrü)")
        done = now()
        lag_h = (pd.Timestamp(done) - pd.Timestamp(first_seen)).total_seconds() / 3600
        row.update({"bitdi_utc": done, "muddet_san": round(time.time() - t0, 1), "sla_saat": round(lag_h, 3),
                    "sla_odenilir": lag_h <= factors.params()["update_sla_hours"],
                    "yuksek_prioritet": ";".join(c["S"][c["S"]["prioritet"] == "yüksək"]["risk_id"]),
                    "xeberdarliq_sayi": len(c["alerts"]), "baseline_id": c["baseline_id"],
                    "status": with_stages("uğurlu", c.get("stages"))})
        STATE.write_text(json.dumps({"fingerprint": fingerprint(), "pending_since": {}, "last_success_utc": done},
                                    ensure_ascii=False, indent=1))
    except Exception as exc:
        row.update({"bitdi_utc": now(), "muddet_san": round(time.time() - t0, 1), "status": f"xəta: {exc!r}"[:300]})
        STATE.write_text(json.dumps({"fingerprint": st["fingerprint"], "pending_since": pending,
                                     "last_failure_utc": row["bitdi_utc"]}, ensure_ascii=False, indent=1))
        traceback.print_exc()
    append_log(row)
    if verbose:
        print(f"{row['status']}: {row['deyisen_girisler'][:120]} — gecikmə {row.get('sla_saat', '—')} saat")
    return row


def daily(fetch: bool = True, backfill: int = 40, verbose: bool = True) -> dict:
    """v2 fast cycle: feeds (global + AZ) → upstream store (rebuilt only if a unit changed) → consensus → monitor."""
    import run_all
    started, t0 = now(), time.time()
    row = {"basladi_utc": started, "tetik": "gündəlik monitor", "ilk_goruldu_utc": started}
    try:
        d = run_all.daily_context(fetch=fetch, backfill=backfill, verbose=verbose)   # same stages as run_all --daily
        stale = bool(d.get("upstream_stale"))
        m = d.get("monitor")
        if m is None:
            raise RuntimeError("gündəlik monitor mərhələsi uğursuz oldu (bax _run_summary_daily.json)")
        D5 = m["D5"]
        warn = D5[D5["signal"].astype(str).str.startswith("xəbərdarlıq")]["indicator"].drop_duplicates()
        row.update({"bitdi_utc": now(), "muddet_san": round(time.time() - t0, 1), "deyisen_girisler":
                    f"monitor: {len(m['D7'])} dəyişiklik" + ("; yuxarı axın yeni vintaj" if stale else ""),
                    "yuksek_prioritet": ";".join(warn)[:200], "xeberdarliq_sayi": len(warn),
                    "status": with_stages("uğurlu", d.get("stages")),
                    "sla_saat": round((time.time() - t0) / 3600, 3), "sla_odenilir": True})
    except Exception as exc:                          # noqa: BLE001
        row.update({"bitdi_utc": now(), "muddet_san": round(time.time() - t0, 1), "status": f"xəta: {exc!r}"[:300]})
        traceback.print_exc()
    append_log(row)
    return row


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-fetch", action="store_true")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--watch", type=float, default=0, help="dəqiqə; 0 — bir dövr")
    ap.add_argument("--daily", action="store_true", help="sürətli: axınlar + monitor (D2–D7)")
    ap.add_argument("--full", action="store_true", help="hamısı: --daily + tam boru xətti və hesabatlar")
    ap.add_argument("--backfill", type=int, default=40, help="AMB məzənnə arxivi: bu dövrdə ən çox sorğu")
    a = ap.parse_args(argv)
    if a.daily or a.full:
        r = daily(fetch=not a.no_fetch, backfill=a.backfill)
        if a.full:
            r2 = cycle(fetch=False, force=True)
            return 0 if str(r.get("status")).startswith("uğurlu") and str(r2.get("status")).startswith("uğurlu") else 1
        return 0 if str(r.get("status")).startswith("uğurlu") else 1
    if a.watch:
        last_fetch = 0.0
        while True:
            fetch = not a.no_fetch and time.time() - last_fetch > 6 * 3600     # feeds at most every 6 h
            cycle(fetch=fetch, force=False)
            if fetch:
                last_fetch = time.time()
            time.sleep(a.watch * 60)
    r = cycle(fetch=not a.no_fetch, force=a.force)
    st = str(r.get("status"))
    return 0 if st.startswith("uğurlu") or st.startswith("dəyişiklik yoxdur") and "xəta" not in st else 1


if __name__ == "__main__":
    sys.exit(main())
