"""bcore.py — shared helpers of the Risk paneli build: paths, robust CSV reading, deterministic compact tables
and the JS bundle writer.

Every number shown in the panel passes through `table()` / `fnum()`: values are read from RiskUnit/output, rounded to
7 significant digits and written with sorted keys, so a rebuild from the same outputs is byte-identical.
"""
import hashlib
import json
import math
import time
from pathlib import Path

import pandas as pd

PANEL = Path(__file__).resolve().parent.parent
UNIT = PANEL.parent
OUT = UNIT / "output"
INP = UNIT / "input"
DOCS = UNIT / "docs"
YEARS = [2026, 2027, 2028, 2029, 2030]

USED = {}          # file name → bundle var(s) it went into
MISSING = []       # required files that do not exist
BUNDLES = {}       # bundle file name → object
_cache = {}


class Missing(Exception):
    pass


def read_retry(path, tries=6, wait=3.0, **kw):
    """Read a CSV that a concurrent run may be rewriting: retry on empty / partial / locked files."""
    for i in range(tries):
        try:
            return pd.read_csv(path, low_memory=False, **kw)
        except (pd.errors.EmptyDataError, pd.errors.ParserError, UnicodeDecodeError, OSError) as e:
            if i == tries - 1:
                raise
            print(f"  ({Path(path).name} oxunmadı: {type(e).__name__}; {wait:.0f} s sonra yenidən)")
            time.sleep(wait)


def csv(name, bundle="", required=True, base=OUT, **kw):
    """DataFrame of output/<name>; records which bundle shows it. Missing required file → recorded (build fails)."""
    p = base / name
    if not p.exists():
        if required:
            MISSING.append(name)
        return None
    key = (str(p), repr(sorted(kw.items())))
    if key not in _cache:
        _cache[key] = read_retry(p, **kw)
    if base == OUT:
        USED.setdefault(name, set()).add(bundle)
    return _cache[key].copy()


def fnum(x, sig=7):
    try:
        f = float(x)
    except (TypeError, ValueError):
        return None
    if math.isnan(f) or math.isinf(f):
        return None
    if f == int(f) and abs(f) < 1e15:
        return int(f)
    return float(f"{f:.{sig}g}")


def cell(v, sig=7):
    if v is None:
        return None
    if isinstance(v, bool):
        return v
    if isinstance(v, (int, float)):
        return fnum(v, sig)
    try:
        if pd.isna(v):
            return None
    except (TypeError, ValueError):
        pass
    if hasattr(v, "item"):
        return cell(v.item(), sig)
    s = str(v)
    return s if s != "" else None


def table(df, cols=None, sig=7, pool=()):
    """Compact table {c: [columns], r: [[row]...]} — the JS side reads it with U.rows().
    pool: columns whose (repeated) strings are replaced by indices into t.p (decoded by U.rows)."""
    if df is None:
        return None
    if cols:
        cols = [c for c in cols if c in df.columns]
        df = df[cols]
    out = {"c": [str(c) for c in df.columns], "r": []}
    pc = [i for i, c in enumerate(df.columns) if c in pool]
    strings, idx = [], {}
    for row in df.itertuples(index=False, name=None):
        r = [cell(v, sig) for v in row]
        for i in pc:
            if r[i] is not None:
                k = str(r[i])
                if k not in idx:
                    idx[k] = len(strings)
                    strings.append(k)
                r[i] = idx[k]
        out["r"].append(r)
    if pc:
        out["p"], out["pc"] = strings, [out["c"][i] for i in pc]
    return out


def lookup(df, key, cols):
    """{key: {col: value}} of the first row per key (to drop repeated label columns from big tables)."""
    d = {}
    for r in df[[key] + [c for c in cols if c in df.columns]].drop_duplicates(key).itertuples(index=False, name=None):
        d[str(r[0])] = {c: cell(v) for c, v in zip(cols, r[1:])}
    return d


def to_json(o):
    return json.dumps(o, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


def bundle(name, var, obj, data_dir=None):
    """Write data/<name>: window.RISK.<var> = {...}; deterministic."""
    data_dir = data_dir or (PANEL / "data")
    data_dir.mkdir(parents=True, exist_ok=True)
    js = to_json(obj)
    txt = (f"/* generated by build_panel.py from RiskUnit/output — do not edit */\n"
           f"window.RISK=window.RISK||{{}};window.RISK.{var}={js};\n")
    (data_dir / name).write_text(txt, encoding="utf-8")
    BUNDLES[name] = (var, obj)
    return len(txt.encode("utf-8"))


def md5_files(paths):
    h = hashlib.md5()
    for p in sorted(paths):
        h.update(Path(p).name.encode())
        h.update(Path(p).read_bytes())
    return h.hexdigest()[:10]


def run_summary():
    p = OUT / "_run_summary_v2.json"
    if not p.exists():
        MISSING.append("_run_summary_v2.json")
        return {}
    USED.setdefault("_run_summary_v2.json", set()).add("core")
    return json.loads(p.read_text(encoding="utf-8"))


def run_summary_daily():
    """_run_summary_daily.json (update.py --daily / run_all.py --daily) — optional; shown on Metod → Son icra."""
    p = OUT / "_run_summary_daily.json"
    if not p.exists():
        return {}
    USED.setdefault("_run_summary_daily.json", set()).add("core")
    return json.loads(p.read_text(encoding="utf-8"))
