# %% [markdown]
# ### 18D. İstifadəçiyə təqdim olunan CSV fayllarındakı hər ingiliscə mətn üçün Azərbaycan dilində sətirlər (`FR12_strings_az.csv`)

# %%
AZ = {}   # English -> Azerbaijani (exact strings); formulaic strings are translated by rules in 18D.3
AZ.update({
 # data-source matrix: pillars, indicators, formulas
 'Entry and exit': 'Giriş və çıxış', 'Concentration and intensity': 'Konsentrasiya və rəqabət intensivliyi', 'Margins and market power': 'Marjalar və bazar gücü',
 'Barriers and regulation': 'Maneələr və tənzimləmə', 'Firm level (Layer B)': 'Müəssisə səviyyəsi (B qatı)',
 'Entry rate by activity group': 'Fəaliyyət qrupları üzrə giriş əmsalı', 'Exit rate by activity group': 'Fəaliyyət qrupları üzrə çıxış əmsalı',
 'Net entry and churn': 'Xalis giriş və dövriyyə (churn)', 'New / liquidated statistical units by NACE section': 'NACE bölmələri üzrə yaradılan / ləğv edilən statistik vahidlər',
 'Entry and exit by economic region': 'İqtisadi rayonlar üzrə giriş və çıxış', 'Cohort-size ratio, ages 1-5 (not a survival rate)': 'Kohort ölçüsü nisbəti, 1–5 yaş (sağ qalma əmsalı deyil)',
 'Number of active units (forecast)': 'Fəal vahidlərin sayı (proqnoz)', 'SME share of output': 'KOS-un buraxılışda payı', 'SME share of employees': 'KOS-un işçi sayında payı',
 'Units by size class': 'Ölçü qrupları üzrə vahidlər', 'HHI / CR4 bounds from size classes': 'Ölçü qruplarından HHI / CR4 hədləri',
 'Taxpayer size classes: count, turnover, receipts, employees': 'Vergi ödəyicilərinin ölçü qrupları: say, dövriyyə, daxilolmalar, işçilər',
 'Active taxpayers by sector': 'Sahələr üzrə aktiv vergi ödəyiciləri', 'Share instability across branches': 'Sahələr arasında payların qeyri-sabitliyi',
 'Regional dispersion of entry; HHI of units across regions': 'Girişin regional dispersiyası; vahidlərin regionlar üzrə HHI-si', 'Price-cost margin proxy': 'Qiymət-xərc marjası (proksi)',
 'Industry margin path (FR10 section forecasts)': 'Sənaye marjası yolu (FR10 bölmə proqnozları)', 'Lerner index (scenario calibration)': 'Lerner indeksi (ssenari kalibrləməsi)',
 'Licences issued': 'Verilmiş lisenziyalar', 'Inspections of businesses (coverage changes over time, F18)': 'Sahibkarlıq subyektlərində yoxlamalar (əhatə zamanla dəyişir, F18)',
 'State share: of industrial output (S5 calibration); of active SMEs (information)': 'Dövlət payı: sənaye buraxılışında (S5 kalibrləməsi); fəal KOS-da (məlumat üçün)',
 'Import penetration by product group': 'Məhsul qrupları üzrə idxalın nüfuzu', 'Firm revenue (market shares, HHI, CR4/CR8, entropy, Gini)': 'Müəssisə gəliri (bazar payları, HHI, CR4/CR8, entropiya, Cini)',
 'Firm entry and exit dates (entry/exit, survival, cohort shares)': 'Müəssisənin giriş və çıxış tarixləri (giriş/çıxış, sağ qalma, kohort payları)',
 'Firm costs (price-cost margin, Boone indicator)': 'Müəssisə xərcləri (qiymət-xərc marjası, Boone indikatoru)', 'Firm attributes (SOE share, region × sector view)': 'Müəssisə xüsusiyyətləri (dövlət payı, region × sahə görünüşü)',
 'newly registered / registered (end-year) × 100; births modelled as a log flow, rate via the stock identity': 'yeni qeydiyyat / qeydiyyatda olanlar (ilin sonu) × 100; doğulmalar log axın kimi modelləşdirilir, əmsal ehtiyat eyniliyi ilə',
 'deregistered / registered × 100': 'qeydiyyatdan çıxarılanlar / qeydiyyatda olanlar × 100', 'entry − exit; entry + exit': 'giriş − çıxış; giriş + çıxış',
 'new or liquidated / units at period end': 'yaradılan və ya ləğv edilən / dövrün sonuna vahidlər', 'new or liquidated / units': 'yaradılan və ya ləğv edilən / vahidlər',
 'active SMEs aged k / aged 1 in the same year (mixes cohort size and survival)': 'eyni ildə k yaşlı fəal KOS / 1 yaşlı fəal KOS (kohort ölçüsü ilə sağ qalmanı qarışdırır)',
 'N(t) = (N(t−1) + births(t)) / (1 + exit rate(t)) (stock-flow identity)': 'N(t) = (N(t−1) + doğulmalar(t)) / (1 + çıxış əmsalı(t)) (ehtiyat-axın eyniliyi)',
 'SME output / total × 100': 'KOS buraxılışı / cəmi × 100', 'SME employees / total × 100': 'KOS işçiləri / cəmi × 100', 'count': 'say',
 'lower Σ S²/n; upper vertex of the box-simplex (Part 8)': 'aşağı hədd Σ S²/n; yuxarı hədd qutu-simpleksin təpəsi (8-ci hissə)',
 'large share of declared turnover; HHI lower bound': 'bəyan edilmiş dövriyyədə iri ödəyicilərin payı; HHI aşağı həddi', '½ Σ|Δs|': '½ Σ|Δs|', 'CV; Σ s²': 'variasiya əmsalı; Σ s²',
 '(VA − compensation) / output × 100': '(ƏDV − əmək haqqı) / buraxılış × 100', '(VA − compensation) / output, B-E': '(ƏDV − əmək haqqı) / buraxılış, B–E',
 'HHI / ε (Cournot)': 'HHI / ε (Kurno)', 'count; per 1000 units': 'say; 1000 vahidə', 'state output / output; state SMEs / active SMEs': 'dövlət buraxılışı / buraxılış; dövlət KOS-ları / fəal KOS',
 'imports / (output − exports + imports)': 'idxal / (buraxılış − ixrac + idxal)', 'Part 17 engine': '17-ci hissənin mühərriki',
 # institutions, tables, granularity, frequency, status, integration
 'DSK': 'DSK', 'DSK via workbook': 'DSK (iş kitabı vasitəsilə)', 'derived': 'hesablanmış', 'derived (DSK)': 'hesablanmış (DSK)', 'DVX': 'DVX', 'FR10': 'FR10',
 'Ministry of Economy': 'İqtisadiyyat Nazirliyi', 'inspection bodies': 'yoxlama orqanları', 'DGK / DSK': 'DGK / DSK',
 'entrepreneurship 006 (+ archived vintages; definition change 2022, F17)': 'sahibkarlıq 006 (+ arxiv versiyaları; 2022-ci il tərif dəyişikliyi, F17)',
 'entrepreneurship 006': 'sahibkarlıq 006', 'st_units 2_1 (+ vintages)': 'st_units 2_1 (+ versiyalar)', "workbook 'Regionlar*' r38/r42/r43; st_units 2_3": "iş kitabı 'Regionlar*' r38/r42/r43; st_units 2_3",
 'entrepreneurship 024-028': 'sahibkarlıq 024–028', 'Part 13': '13-cü hissə', 'entrepreneurship 012 (+ vintages)': 'sahibkarlıq 012 (+ versiyalar)',
 'entrepreneurship 013 (+ vintages)': 'sahibkarlıq 013 (+ versiyalar)', 'st_units 1_3, 1_4; entrepreneurship 005': 'st_units 1_3, 1_4; sahibkarlıq 005', 'Part 8': '8-ci hissə',
 "workbook 'DVX üzrə göstəricilər' r111-r126": "iş kitabı 'DVX üzrə göstəricilər' r111–r126", "workbook 'DVX üzrə göstəricilər' r131-r145": "iş kitabı 'DVX üzrə göstəricilər' r131–r145",
 'FR10_branch_shares_history.csv': 'FR10_branch_shares_history.csv', 'Part 7': '7-ci hissə', 'national accounts 013': 'milli hesablar 013', 'FR10_forecast_sections.csv': 'FR10_forecast_sections.csv',
 'Part 15': '15-ci hissə', "workbook 'Verilmiş lisenziyalar'": "iş kitabı 'Verilmiş lisenziyalar'", "workbook 'Aparılan yoxlamalar'": "iş kitabı 'Aparılan yoxlamalar'",
 'industry 010_2 via FR10_ownership.csv (output, 2005-2025); entrepreneurship 005 (SMEs, 2023-2024)': 'sənaye 010_2, FR10_ownership.csv vasitəsilə (buraxılış, 2005–2025); sahibkarlıq 005 (KOS, 2023–2024)',
 'customs data by HS × NACE': 'HS × NACE üzrə gömrük məlumatı', 'business register: revenue': 'biznes reyestri: gəlir', 'business register: registration_date / liquidation_date': 'biznes reyestri: qeydiyyat / ləğv tarixi',
 'business register: cost_of_sales / operating_costs': 'biznes reyestri: satışın maya dəyəri / əməliyyat xərcləri', 'business register: ownership, region, size_class': 'biznes reyestri: mülkiyyət, region, ölçü qrupu',
 '11 activity groups': '11 fəaliyyət qrupu', '19 NACE sections': '19 NACE bölməsi', '14 regions': '14 iqtisadi rayon', '11 groups × size': '11 qrup × ölçü', 'groups, regions': 'qruplar, regionlar',
 '11 groups × micro/small/medium': '11 qrup × mikro/kiçik/orta', 'section / region × size': 'bölmə / region × ölçü', '11 groups': '11 qrup', 'economy, 4 classes': 'iqtisadiyyat, 4 qrup',
 '5 sectors (others empty)': '5 sahə (digərləri boşdur)', '24 manufacturing branches': 'emal sənayesinin 24 sahəsi', '19 sections / 11 groups': '19 bölmə / 11 qrup', 'sections B-E': 'B–E bölmələri',
 'sector': 'sahə', '24 licence types → groups': '24 lisenziya növü → qruplar', '19 bodies': '19 orqan', 'industry; 11 groups': 'sənaye; 11 qrup', 'firm × NACE × region × year': 'müəssisə × NACE × region × il',
 'annual': 'illik', 'annual, half-year': 'illik, yarımillik', 'snapshot (1 July 2026); 2023-2024': 'an (1 iyul 2026); 2023–2024', 'on demand': 'tələb əsasında', 'semi-annual': 'yarımillik',
 'available now': 'hazırda mövcuddur', 'not available': 'mövcud deyil', 'requested': 'sorğu göndərilib',
 'archived DSK vintages (scripted)': 'DSK-nın arxiv versiyaları (skriptlə)', 'workbook upload (Ministry)': 'iş kitabının yüklənməsi (Nazirlik)',
 'file download (DSK website, scripted)': 'faylın yüklənməsi (DSK saytı, skriptlə)', 'MIIS internal (FR module output)': 'MİİS daxili (FR modulunun nəticəsi)',
 'data-sharing agreement with the State Customs Committee': 'Dövlət Gömrük Komitəsi ilə məlumat mübadiləsi razılaşması',
 'data-sharing agreement with DSK (business register extract)': 'DSK ilə məlumat mübadiləsi razılaşması (biznes reyestrindən çıxarış)',
})
