# %%
AZ.update({k: v for k, v in [
 # scenarios, merger screens
 ('Entry-barrier reduction / licensing simplification', 'Giriş maneələrinin azaldılması / lisenziyalaşdırmanın sadələşdirilməsi'), ('Entry of a 4th mobile operator', 'Dördüncü mobil operatorun girişi'),
 ('Merger of two firms', 'İki müəssisənin birləşməsi'), ('Merger of two banks', 'İki bankın birləşməsi'), ('Cost shock / excise or tax increase', 'Xərc şoku / aksiz və ya vergi artımı'),
 ('Energy-cost shock', 'Enerji xərcləri şoku'), ('Import competition (tariff cut)', 'İdxal rəqabəti (tarifin azaldılması)'),
 ('SOE partial privatisation (mixed oligopoly)', 'Dövlət müəssisəsinin qismən özəlləşdirilməsi (qarışıq oliqopoliya)'), ('SOE full privatisation (mixed oligopoly)', 'Dövlət müəssisəsinin tam özəlləşdirilməsi (qarışıq oliqopoliya)'),
 ('one additional symmetric-equivalent competitor (ΔN = +1)', 'bir əlavə simmetrik-ekvivalent rəqib (ΔN = +1)'), ('ΔN = +1 symmetric-equivalent competitor', 'ΔN = +1 simmetrik-ekvivalent rəqib'),
 ('merging shares 10% and 5%; HHI used >= 0.10² + 0.05²', 'birləşən paylar 10% və 5%; istifadə olunan HHI ≥ 0.10² + 0.05²'), ('merging asset shares 8% and 6%; HHI used >= 0.08² + 0.06²', 'birləşən aktiv payları 8% və 6%; istifadə olunan HHI ≥ 0.08² + 0.06²'),
 ('per-unit cost +5% of the initial price, all firms', 'vahid xərc ilkin qiymətin +5%-i, bütün müəssisələr'), ('per-unit cost +5% of the initial price, all producers', 'vahid xərc ilkin qiymətin +5%-i, bütün istehsalçılar'),
 ('import share 30% -> 40%, import supply elasticity η = 2', 'idxal payı 30% → 40%, idxal təklifinin elastikliyi η = 2'), ('import share 20% -> 30%, η = 2', 'idxal payı 20% → 30%, η = 2'),
 ('σ = 21.9% (industry), λ: 0 -> 0.5', 'σ = 21.9% (sənaye), λ: 0 → 0.5'), ('σ = 21.9% (industry), λ: 0 -> 1.0', 'σ = 21.9% (sənaye), λ: 0 → 1.0'),
 ('σ = 35.1% (manufacturing), λ: 0 -> 0.5', 'σ = 35.1% (emal sənayesi), λ: 0 → 0.5'), ('σ = 35.1% (manufacturing), λ: 0 -> 1.0', 'σ = 35.1% (emal sənayesi), λ: 0 → 1.0'),
 ('Layer-A size-class bounds (Part 8), 2024', 'A qatının ölçü qrupu hədləri (8-ci hissə), 2024'),
 ('ASSUMPTION: 3 operators, subscriber shares ≈ 50-55 / 25-30 / 20% (approximate public reports) -> HHI 3,300-4,000', 'FƏRZİYYƏ: 3 operator, abunəçi payları ≈ 50–55 / 25–30 / 20% (təxmini açıq hesabatlar) → HHI 3 300–4 000'),
 ('ASSUMPTION: ~22 banks, top-5 ≈ 60% of assets (approximate, CBAR annual reports) -> HHI 800-1,300; replace with CBAR concentration data', 'FƏRZİYYƏ: ~22 bank, ilk 5 bank aktivlərin ≈ 60%-i (təxmini, AMB illik hesabatları) → HHI 800–1 300; AMB konsentrasiya məlumatı ilə əvəz edilməlidir'),
 ('ASSUMPTION: 2-3 domestic integrated producers plus imports (approximate) -> domestic HHI 3,500-5,500', 'FƏRZİYYƏ: 2–3 yerli inteqrasiya olunmuş istehsalçı və idxal (təxmini) → daxili HHI 3 500–5 500'),
 ('0.5-2.0 (FR5 services system: 1.0)', '0.5–2.0 (FR5 xidmətlər sistemi: 1.0)'), ('Cournot θ = 1; θ = 0.5', 'Kurno θ = 1; θ = 0.5'), ('linear', 'xətti'), ('illustrative', 'illüstrativ'),
 ('unlikely to have adverse effects', 'mənfi təsir ehtimalı azdır'), ('potentially raises significant concerns', 'potensial olaraq ciddi narahatlıq yaradır'), ('presumed to enhance market power', 'bazar gücünü artırdığı ehtimal edilir'),
 ('no presumption', 'ehtimal yoxdur'), ('concern', 'narahatlıq'),
 # identity checks, pipeline and swap tests
 ('register sections add to published totals (11 files)', 'reyestr bölmələri dərc olunmuş cəmlərə bərabərdir (11 fayl)'), ('entrepreneurship 11 groups add to total (006)', 'sahibkarlığın 11 qrupu cəmə bərabərdir (006)'),
 ('national accounts: output − IC = VA (all sections, years)', 'milli hesablar: buraxılış − aralıq istehlak = ƏDV (bütün bölmələr, illər)'), ('size classes sum to commercial organisations (1_3 vs 1_1)', 'ölçü qrupları kommersiya təşkilatlarının sayına bərabərdir (1_3 vs 1_1)'),
 ('region panel totals = register totals 2021, 2024, 2025', 'regional panelin cəmləri = reyestr cəmləri (2021, 2024, 2025)'),
 ('HHI lower <= floor variants <= headline upper; CR4 lower <= CR4 upper (all groups, years)', 'HHI aşağı hədd ≤ döşəmə variantları ≤ əsas yuxarı hədd; CR4 aşağı ≤ CR4 yuxarı (bütün qruplar, illər)'),
 ('CR4 bounds consistent with HHI bounds: CR4^2/4 <= HHI_upper (all groups, years)', 'CR4 hədləri HHI hədləri ilə uzlaşır: CR4²/4 ≤ HHI_yuxarı (bütün qruplar, illər)'),
 ('stock-flow identity N(t) = N(t-1) + births(t) - deaths(t) in every forecast path', 'ehtiyat-axın eyniliyi N(t) = N(t−1) + doğulmalar(t) − ölümlər(t) hər proqnoz yolunda'),
 ('projected upper bounds evolve continuously (max year-on-year change < 25%)', 'proqnozlaşdırılan yuxarı hədlər fasiləsiz dəyişir (illik dəyişmə < 25%)'),
 ('Cournot calibration reproduces P = 1, Q = 1 at the calibration point', 'Kurno kalibrləməsi kalibrləmə nöqtəsində P = 1, Q = 1 verir'), ('linear Cournot pass-through equals N/(N+θ), θ = 1.0', 'xətti Kurno ötürülməsi N/(N+θ)-ya bərabərdir, θ = 1.0'),
 ('linear Cournot pass-through equals N/(N+θ), θ = 0.5', 'xətti Kurno ötürülməsi N/(N+θ)-ya bərabərdir, θ = 0.5'),
 ('mixed oligopoly: calibration reproduces P = 1, Q = 1, SOE share σ; λ = 0 leaves the equilibrium unchanged', 'qarışıq oliqopoliya: kalibrləmə P = 1, Q = 1 və dövlət payı σ verir; λ = 0 tarazlığı dəyişmir'),
 ('scenario welfare: ΔCS has the opposite sign of Δprice in every run', 'ssenari rifahı: ΔİR hər hesablamada Δqiymətin əks işarəsindədir'), ('mixed oligopoly: every calibration reproduces P = 1, Q = 1 and σ', 'qarışıq oliqopoliya: hər kalibrləmə P = 1, Q = 1 və σ verir'),
 ('aggregate N = sum of group N in every scenario-year', 'aqreqat N = qrupların N cəmi (hər ssenari-il)'), ('fan: p5 <= p50 <= p95 for every series', 'zolaq: hər sıra üçün p5 ≤ p50 ≤ p95'),
 ('SME + large output shares = 100 (all groups, years)', 'KOS + iri müəssisə payları = 100 (bütün qruplar, illər)'), ('early-warning score in [0, 1]', 'erkən xəbərdarlıq balı [0, 1] aralığındadır'),
 ('HHI >= 10000 / N in every market', 'hər bazarda HHI ≥ 10000 / N'), ('CR4 <= CR8 <= 100', 'CR4 ≤ CR8 ≤ 100'), ('entropy <= ln N', 'entropiya ≤ ln N'),
 ('shares add to 1 in every national division market with revenue', 'gəliri olan hər milli bölmə bazarında paylar cəmi 1-dir'), ('Kaplan-Meier survival non-increasing and in [0, 1]', 'Kaplan–Meyer sağ qalma əyrisi artmır və [0, 1] aralığındadır'),
 ('calibration: births, deaths, revenue and SME revenue shares reproduce DSK where published (max |relative error| %)', 'kalibrləmə: doğulmalar, ölümlər, gəlir və KOS gəlir payları dərc olunduğu yerdə DSK ilə üst-üstə düşür (maks. |nisbi xəta| %)'),
 ('DGP check: Boone slope negative (efficient firms larger) in >= 90% of section-years', 'MYP yoxlaması: bölmə-illərin ≥ 90%-ində Boone meyli mənfidir (səmərəli müəssisələr böyükdür)'),
 ('DGP check: low-Pareto-alpha sections more concentrated (median HHI ratio)', 'MYP yoxlaması: aşağı Pareto-α bölmələri daha konsentrasiyalıdır (median HHI nisbəti)'),
 ('real-named file with neutral data_status -> DATA_MODE = REAL', 'neytral data_status ilə real adlı fayl → DATA_MODE = REAL'), ('REAL file passes the validator (0 hard errors)', 'REAL fayl yoxlamadan keçir (0 ciddi səhv)'),
 ('REAL mode writes FR12_FIRM_* only, without watermark; identity tests pass; Layer-B econometrics run in REAL mode (FR12_FIRM_econ_*)', 'REAL rejimi yalnız su nişanı olmayan FR12_FIRM_* yazır; eynilik testləri keçir; B qatının ekonometrikası REAL rejimdə işləyir (FR12_FIRM_econ_*)'),
 ('Azerbaijani headers (xlsx) load and validate', 'Azərbaycan dilində başlıqlar (xlsx) yüklənir və yoxlanılır'), ('BUSREG_PATH environment variable has priority over the real-named file', 'BUSREG_PATH mühit dəyişəni real adlı fayldan üstündür'),
 ('register without a weight column: full engine runs (weights default to 1)', 'çəki sütunu olmayan reyestr: mühərrik tam işləyir (çəkilər 1 qəbul edilir)'),
 ('weights honoured: weighted file = expanded unweighted file (HHI, CR4/CR8, entry/exit, KM, Boone n, PCM)', 'çəkilər nəzərə alınır: çəkili fayl = genişləndirilmiş çəkisiz fayl (HHI, CR4/CR8, giriş/çıxış, KM, Boone n, PCM)'),
 ('broken file: missing required column reported as fatal', 'xətalı fayl: çatışmayan məcburi sütun ciddi səhv kimi göstərilir'),
 ('broken file: negative revenue and liquidation before registration flagged per row; the run stops', 'xətalı fayl: mənfi gəlir və qeydiyyatdan əvvəl ləğv sətir-sətir göstərilir; icra dayanır'),
 ('generator never writes the real file name; project directory scanned for real-named files', 'generator heç vaxt real fayl adını yazmır; layihə qovluğu real adlı fayllar üçün yoxlanılır'),
 # calibration table, schema, statuses
 ('SME share of employees, %', 'KOS-un işçi sayında payı, %'), ('SME share of revenue, %', 'KOS-un gəlirdə payı, %'), ('active units, end of year', 'fəal vahidlər, ilin sonu'), ('births', 'doğulmalar'), ('deaths', 'ölümlər'),
 ('revenue (thsd AZN) = output', 'gəlir (min AZN) = buraxılış'), ('size mix: large share of units, %', 'ölçü strukturu: iri vahidlərin payı, %'), ('size mix: medium share of units, %', 'ölçü strukturu: orta vahidlərin payı, %'),
 ('size mix: micro share of units, %', 'ölçü strukturu: mikro vahidlərin payı, %'), ('size mix: small share of units, %', 'ölçü strukturu: kiçik vahidlərin payı, %'), ('activity group', 'fəaliyyət qrupu'), ('region', 'region'), ('section', 'bölmə'),
 ('exact except where the 251-employee floor of large units binds', 'dəqiq (iri vahidlərin 251 işçi döşəməsi məhdudlaşdırdığı hallar istisna)'), ('exact (output base)', 'dəqiq (buraxılış bazası)'), ('exact 2025; earlier via stock-flow', 'dəqiq 2025; əvvəlki illər ehtiyat-axın ilə'),
 ('exact 2025; earlier via stock-flow (F5)', 'dəqiq 2025; əvvəlki illər ehtiyat-axın ilə (F5)'), ('exact', 'dəqiq'), ('exact where published', 'dərc olunduğu yerdə dəqiq'), ('approximate (1 July 2026 snapshot)', 'təxmini (1 iyul 2026 vəziyyəti)'),
 ('str', 'mətn'), ('int', 'tam ədəd'), ('float', 'həqiqi ədəd'), ('date', 'tarix'), ('synthetic marker; any other value or no column = REAL data', 'sintetik nişan; başqa dəyər və ya sütunun olmaması = REAL məlumat'),
 ('unique per enterprise, pseudonymised (never the VÖEN)', 'hər müəssisə üçün unikal, psevdonimləşdirilmiş (heç vaxt VÖEN deyil)'), ('reporting year', 'hesabat ili'), ('NACE Rev.2 division, 2 digits, sections A-S and U', 'NACE Rev.2 bölməsi, 2 rəqəm, A–S və U'),
 ('one of the 14 economic regions', '14 iqtisadi rayondan biri'), ('state | municipal | private | foreign | joint', 'dövlət | bələdiyyə | özəl | xarici | birgə'), ('micro | small | medium | large (statutory classes)', 'mikro | kiçik | orta | iri (qanuni qruplar)'),
 ('>= 0', '≥ 0'), ('state registration date (entry); <= 31 Dec of year', 'dövlət qeydiyyatı tarixi (giriş); ilin 31 dekabrından gec deyil'), ('liquidation date (exit); empty while active; >= registration date', 'ləğv tarixi (çıxış); fəal olduqda boş; qeydiyyat tarixindən gec'),
 ('active | liquidated (liquidated only in the year of liquidation)', 'fəal | ləğv edilmiş (yalnız ləğv ilində)'), ('LLC | JSC | state enterprise | other', 'MMC | SC | dövlət müəssisəsi | digər'), ('>= 0, <= revenue', '≥ 0, ≤ gəlir'),
 ('HS / PRODCOM codes, ";"-separated', 'HS / PRODCOM kodları, ";" ilə ayrılmış'), ('>= 0 (price-cost margin, Boone indicator)', '≥ 0 (qiymət-xərc marjası, Boone indikatoru)'),
 ('number of identical enterprises the row stands for; 1 (or absent) in a census register', 'sətrin təmsil etdiyi eyni müəssisələrin sayı; tam reyestrdə 1 (və ya yoxdur)'), ('generator', 'generator'), ('DSK register', 'DSK reyestri'),
 ('DSK register / DVX', 'DSK reyestri / DVX'), ('DSK register / DSMF', 'DSK reyestri / DSMF'), ('State Customs Committee', 'Dövlət Gömrük Komitəsi'), ('DSK / Customs', 'DSK / Gömrük'), ('DVX (link by firm_id to FR10 panel)', 'DVX (FR10 panelinə firm_id ilə bağlantı)'),
 ('generator / sample design', 'generator / seçmə dizaynı'), ('coherent', 'uyğundur'), ('not applied (vacuous: 1 transition per unit)', 'tətbiq olunmayıb (boş: hər vahiddə 1 keçid)'), ('dropped (incoherent)', 'çıxarılıb (uyğunsuz)'),
 ('log births', 'log doğulmalar'), ('exit rate, %', 'çıxış əmsalı, %'), ('entry rate, % (births / identity stock)', 'giriş əmsalı, % (doğulmalar / eynilik ehtiyatı)'), ('log-odds SME output share', 'KOS buraxılış payının log-odds-u'),
 ('entry rate, %', 'giriş əmsalı, %'), ('stock growth, % a year', 'ehtiyatın artımı, ildə %'), ('outside historical range', 'tarixi intervaldan kənar'), ('differs from recent mean by >25%', 'son ortadan 25%-dən çox fərqlənir'),
 ('insufficient data', 'məlumat kifayət deyil'), ('iid', 'müstəqil eyni paylanmış (iid)'), ('random walk', 'təsadüfi gəzişmə'), ('no driver (null)', 'sürücü yoxdur (sıfır model)'), ('see Part 14', '14-cü hissəyə baxın'),
 ('archived vintage', 'arxiv versiyası'), ('DSK current', 'DSK cari fayl'), ('FR10 download (read only)', 'FR10 yükləməsi (yalnız oxumaq üçün)'), ('present', 'mövcuddur'), ('downloaded', 'yüklənib'), ('shared with FR10', 'FR10 ilə ortaq'),
]})
