# %%
AZ.update({
 # analytical use, presentation, alternatives
 'structural births model (Part 11-13)': 'struktur doğulma modeli (11–13-cü hissələr)', 'structural exit model': 'struktur çıxış modeli', 'early warning': 'erkən xəbərdarlıq',
 'section monitoring; Layer-B calibration': 'bölmə monitorinqi; B qatının kalibrləməsi', 'regional entry/exit model; heat map': 'regional giriş/çıxış modeli; istilik xəritəsi',
 'information only (not in the early-warning composite)': 'yalnız məlumat üçün (erkən xəbərdarlıq balına daxil deyil)', 'forecast': 'proqnoz',
 'concentration bounds; share projection': 'konsentrasiya hədləri; payların proyeksiyası', 'size structure': 'ölçü strukturu', 'concentration bounds; Layer-B calibration': 'konsentrasiya hədləri; B qatının kalibrləməsi',
 'concentration monitoring; early warning': 'konsentrasiya monitorinqi; erkən xəbərdarlıq', 'economy-wide concentration': 'iqtisadiyyat üzrə konsentrasiya', 'cross-check of entry dynamics': 'giriş dinamikasının çarpaz yoxlanışı',
 'early warning (falling mobility)': 'erkən xəbərdarlıq (mobilliyin azalması)', 'regional monitoring': 'regional monitorinq',
 'entry-model driver; early warning (margins up, entry down)': 'giriş modelinin sürücüsü; erkən xəbərdarlıq (marja artır, giriş azalır)',
 'margin driver path for industry if a rule selects the margin; the current rules do not, so it is not used in this run': 'qayda marjanı seçərsə sənaye üçün marja yolu; cari qaydalar seçmir, bu icrada istifadə olunmur',
 'scenario simulator': 'ssenari simulyatoru', 'entry indicator (information; not a barrier flag)': 'giriş göstəricisi (məlumat; maneə bayrağı deyil)', 'information only': 'yalnız məlumat üçün',
 'mixed-oligopoly scenario (S5); information': 'qarışıq oliqopoliya ssenarisi (S5); məlumat', 'tariff / import-competition scenario': 'tarif / idxal rəqabəti ssenarisi', 'Layer-B competition engine': 'B qatının rəqabət mühərriki',
 'time-series chart with forecast fan': 'proqnoz zolaqlı zaman sırası qrafiki', 'dashboard KPI card': 'idarə paneli KPI kartı', 'heat map section × year': 'istilik xəritəsi bölmə × il',
 'map; region × year heat map': 'xəritə; region × il istilik xəritəsi', 'table': 'cədvəl', 'forecast fan': 'proqnoz zolağı', 'stacked bar; trend': 'yığılmış sütun; trend', 'stacked bar': 'yığılmış sütun',
 'concentration bounds chart (range bars)': 'konsentrasiya hədləri qrafiki (interval sütunları)', 'KPI card; trend': 'KPI kartı; trend', 'trend': 'trend', 'map': 'xəritə', 'trend; quadrant': 'trend; kvadrant',
 'simulator with assumptions panel': 'fərziyyələr paneli olan simulyator', 'trend; table': 'trend; cədvəl', 'bar': 'sütun', 'simulator input': 'simulyator girişi', 'firm-level market structure view': 'müəssisə səviyyəsində bazar strukturu görünüşü',
 '-': '-', 'Kaplan-Meier survival by cohort from the register (Layer B)': 'reyestr üzrə kohortlar üçün Kaplan–Meyer sağ qalma əyrisi (B qatı)', 'firm-level HHI (Layer B)': 'müəssisə səviyyəsində HHI (B qatı)',
 'register counts (DSK)': 'reyestr sayları (DSK)', 'inspection register with NACE codes and constant coverage': 'NACE kodları və sabit əhatəli yoxlamalar reyestri',
 'SOE revenue share by market from the register (Layer B)': 'reyestrdən bazarlar üzrə dövlət müəssisələrinin gəlir payı (B qatı)', 'FR5/FR1 import aggregates; literature fringe shares': 'FR5/FR1 idxal aqreqatları; ədəbiyyatdakı kənar paylar',
 'Layer-A bounds and rates (this module)': 'A qatının hədləri və əmsalları (bu modul)',
 # gaps and alternatives
 'Firm-level revenue by NACE × region (DSK business register)': 'NACE × region üzrə müəssisə səviyyəsində gəlir (DSK biznes reyestri)', 'Firm entry and exit dates': 'Müəssisələrin giriş və çıxış tarixləri',
 'Long time series of entry/exit by activity': 'Fəaliyyət növləri üzrə giriş/çıxışın uzun zaman sırası', 'Firm costs (cost of sales, operating costs)': 'Müəssisə xərcləri (satışın maya dəyəri, əməliyyat xərcləri)',
 'Import penetration by sector': 'Sahələr üzrə idxalın nüfuzu', 'Narrow product markets': 'Dar məhsul bazarları', 'Licensing and inspections by NACE': 'NACE üzrə lisenziyalar və yoxlamalar', 'DVX micro-taxpayer rows': 'DVX mikro vergi ödəyicisi sətirləri',
 'no firm HHI/CR4, no market-share mobility, no Boone indicator': 'müəssisə HHI/CR4-ü, bazar payı mobilliyi, Boone indikatoru yoxdur', 'no cohort survival, no entrant/exiter size': 'kohort sağ qalması, giriş/çıxış edənlərin ölçüsü yoxdur',
 'only 5 annual observations per group (2019-2024, no 2021); low test power': 'hər qrup üzrə yalnız 5 illik müşahidə (2019–2024, 2021 yoxdur); testlərin gücü aşağıdır',
 'no firm price-cost margin or Boone indicator': 'müəssisə qiymət-xərc marjası və ya Boone indikatoru yoxdur', 'import-competition scenarios need a domestic-share calibration': 'idxal rəqabəti ssenariləri daxili payın kalibrləməsini tələb edir',
 'activity groups understate concentration in product markets': 'fəaliyyət qrupları məhsul bazarlarında konsentrasiyanı azaldılmış göstərir', 'barrier proxies mapped to groups by licence type': 'maneə proksiləri lisenziya növünə görə qruplara uyğunlaşdırılıb',
 'micro rows duplicate budget organisations (F8)': 'mikro sətirlər büdcə təşkilatlarını təkrarlayır (F8)', 'size-class concentration bounds (Part 8); branch-share instability from FR10': 'ölçü qrupları üzrə konsentrasiya hədləri (8-ci hissə); FR10-dan sahə paylarının qeyri-sabitliyi',
 'DSK 006 registration flows; 024-028 age structure; register flows 2_1/2_3': 'DSK 006 qeydiyyat axınları; 024–028 yaş strukturu; reyestr axınları 2_1/2_3', 'archived DSK vintages (Part 4)': 'DSK-nın arxiv versiyaları (4-cü hissə)',
 'section PCM proxy from national accounts': 'milli hesablardan bölmə üzrə PCM proksisi', 'literature fringe shares; FR1/FR5 aggregate imports': 'ədəbiyyatdakı kənar paylar; FR1/FR5 aqreqat idxalı',
 'FR10 product location shares; licence types': 'FR10 məhsul yerləşmə payları; lisenziya növləri', 'mapping of 24 licence types to 11 groups (Part 5)': '24 lisenziya növünün 11 qrupa uyğunlaşdırılması (5-ci hissə)',
 'micro excluded from DVX concentration': 'mikro ödəyicilər DVX konsentrasiyasından çıxarılıb', 'bounds are wide where SMEs dominate; activity groups are broader than antitrust markets': 'KOS üstünlük təşkil etdikdə hədlər genişdir; fəaliyyət qrupları antiinhisar bazarlarından genişdir',
 '006 counts registrations incl. individual entrepreneurs, not market entry; register exit understates exit (F14)': '006 bazara girişi deyil, fərdi sahibkarlar daxil qeydiyyatları sayır; reyestr üzrə çıxış çıxışı azaldılmış göstərir (F14)',
 'definitions changed between vintages ("newly created" → "newly registered")': 'versiyalar arasında tərif dəyişib ("yeni yaradılmış" → "yeni qeydiyyatdan keçmiş")', 'aggregate PCM mixes capital returns with rents': 'aqreqat PCM kapital gəlirini renta ilə qarışdırır',
 'not sector-specific': 'sahəyə xas deyil', 'partial coverage': 'qismən əhatə', 'several types are cross-sector': 'bir neçə növ sahələrarasıdır', 'economy-wide bound slightly overstated': 'iqtisadiyyat üzrə hədd bir qədər şişirdilib',
 'confirm the register extract (requested 24 Aug 2026); agree pseudonymised firm_id and annual delivery': 'reyestr çıxarışını təsdiqləmək (24 avqust 2026 sorğusu); psevdonimləşdirilmiş firm_id və illik ötürülmə barədə razılaşmaq',
 'include registration/liquidation dates in the register extract': 'reyestr çıxarışına qeydiyyat/ləğv tarixlərini daxil etmək', 'ask DSK for the 2010-2025 series of table 006 and 2_1 in one consistent vintage': 'DSK-dan 006 və 2_1 cədvəllərinin 2010–2025 sırasını vahid versiyada istəmək',
 'link the FR10 Tax Service panel by firm_id, or add cost fields to the register extract': 'FR10 Vergi Xidməti panelini firm_id ilə birləşdirmək və ya reyestr çıxarışına xərc sahələri əlavə etmək',
 'customs HS × NACE concordance from the State Customs Committee': 'Dövlət Gömrük Komitəsindən HS × NACE uyğunluq cədvəli',
 'agree priority markets (fuel, cement, telecom, pharmaceuticals, retail chains) for product-level data': 'məhsul səviyyəli məlumat üçün prioritet bazarları razılaşdırmaq (yanacaq, sement, telekom, əczaçılıq, pərakəndə şəbəkələr)',
 'request licence and inspection registers with NACE codes': 'NACE kodları ilə lisenziya və yoxlama reyestrlərini istəmək', 'Tax Service to correct rows r123-r126': 'Vergi Xidməti r123–r126 sətirlərini düzəltməlidir',
 # no-AR constructs
 'Stock of active units N(t)': 'Fəal vahidlərin ehtiyatı N(t)', 'Entry rate': 'Giriş əmsalı', 'Anchoring on the last residual (add-factor)': 'Son qalığa ankerləmə (düzəliş əmsalı)',
 'Definition break and impulses': 'Tərif qırılması və impulslar', 'Sector demand growth Δln VA(t)': 'Sektor tələbinin artımı Δln ƏDV(t)', 'First-difference coherence check': 'Birinci fərqlər üzrə uyğunluq yoxlaması',
 'Random-walk benchmark': 'Təsadüfi gəzişmə müqayisə modeli', 'Constant (mean) rate benchmark / null': 'Sabit (orta) əmsal müqayisə modeli / sıfır model', 'Unit fixed effects': 'Vahid sabit effektləri',
 'Uncertainty bands': 'Qeyri-müəyyənlik zolaqları', 'Synthetic register (Layer B)': 'Sintetik reyestr (B qatı)',
 'identity': 'eynilik', 'model': 'model', 'driver': 'sürücü', 'diagnostic': 'diaqnostika', 'benchmark': 'müqayisə modeli', 'benchmark / combination partner': 'müqayisə modeli / kombinasiya tərəfdaşı', 'bands': 'zolaqlar', 'test data': 'test məlumatı',
 'births(t) / N(t)': 'doğulmalar(t) / N(t)', 'growth rate of an FR1 driver': 'FR1 sürücüsünün artım tempi', 'Δentry(t) on Δdrivers(t)': 'Δgiriş(t) Δsürücülər(t) üzrə', 'entry(t+h) = entry(t)': 'giriş(t+h) = giriş(t)',
 'unit mean over the estimation window': 'qiymətləndirmə pəncərəsi üzrə vahid ortası', 'a_i estimated on the training window': 'a_i təlim pəncərəsində qiymətləndirilir', 'firm size evolves by a stated data-generating process': 'müəssisə ölçüsü bəyan edilmiş məlumat yaratma prosesi ilə dəyişir',
 'deterministic dummies, not lags': 'deterministik dummy-lər, gecikmələr deyil', 'a transformation of an exogenous driver, not of the dependent variable': 'asılı dəyişənin deyil, ekzogen sürücünün çevrilməsi',
 'diagnostic only: the forecast never uses the lagged rate': 'yalnız diaqnostika: proqnoz heç vaxt gecikmiş əmsaldan istifadə etmir', 'benchmark only, required by NFR1; never used as the forecast': 'yalnız müqayisə modeli (NFR1 tələbi); heç vaxt proqnoz kimi istifadə olunmur',
 'the unit fixed effect itself: a level, not a dynamic': 'vahidin sabit effektinin özü: dinamika deyil, səviyyə', 'time-invariant intercepts, no dynamics': 'zamandan asılı olmayan sabitlər, dinamika yoxdur',
 'resampled historical errors; no residual AR is estimated or imposed': 'yenidən seçilmiş tarixi xətalar; qalıq AR qiymətləndirilmir və tətbiq olunmur', 'test data only; the engine estimates no dynamic model': 'yalnız test məlumatı; mühərrik dinamik model qiymətləndirmir',
 'derived from the births forecast and the identity stock; never modelled on its own past': 'doğulma proqnozundan və eynilik ehtiyatından alınır; heç vaxt öz keçmişi üzrə modelləşdirilmir',
 "accounting identity (like FR1's capital stock): births and the exit rate are forecast structurally, the stock is their sum": 'mühasibat eyniliyi (FR1-in kapital ehtiyatı kimi): doğulmalar və çıxış əmsalı struktur proqnozlaşdırılır, ehtiyat onların cəmidir',
 'the FR1–FR10 add-factor convention: the last residual is held constant, no dynamics are estimated; the implied random-walk weight of every rule is reported in Part 12': 'FR1–FR10 düzəliş əmsalı konvensiyası: son qalıq sabit saxlanılır, dinamika qiymətləndirilmir; hər qaydanın təsadüfi gəzişmə çəkisi 12-ci hissədə verilir',
 'N(t) = (N(t−1) + births(t)) / (1 + exit rate(t)), i.e. N(t) = N(t−1) + B(t) − D(t) with D on the end-year stock': 'N(t) = (N(t−1) + doğulmalar(t)) / (1 + çıxış əmsalı(t)), yəni N(t) = N(t−1) + B(t) − D(t), D ilin sonundakı ehtiyat üzrə',
 'forecast = model + (y_last − fitted_last); implied weight on the last observation 1 (0.5 in a combination)': 'proqnoz = model + (y_son − qiymətləndirilmiş_son); son müşahidəyə çəki 1 (kombinasiyada 0.5)',
 'brk = 1 from 2022 (006 definition change); 2022 exit impulse': 'brk = 1 (2022-dən; 006 tərif dəyişikliyi); 2022 çıxış impulsu',
 'historical residual pairs e_h = w(u_{s+h} − u_s) + (1 − w)u_{s+h}, joint across units and equations; parameter draws; FR1 draws': 'tarixi qalıq cütləri e_h = w(u_{s+h} − u_s) + (1 − w)u_{s+h}, vahidlər və tənliklər üzrə birgə; parametr çəkilişləri; FR1 çəkilişləri',
})
