/* p_cmp.js — Metodların müqayisəsi (NFR2): the same scenario through MikroUnit / CAEM / OxLon / IO / microsimulation —
   effects side by side per indicator and horizon, spread, sign agreement and the Azerbaijani explanation of differences. */
(function () {
  'use strict';
  var U = window.U, M = ['micro', 'caem', 'oxlon', 'riskfx', 'io', 'microsim'];
  U.pages.muqayise = function (v) {
    v.innerHTML = U.head('NFR2 — eyni ssenari üçün ən azı iki metod', 'Metodların müqayisəsi', 'Eyni siyasət ssenarisi müxtəlif modellərlə hesablanır: MikroUnit struktur zənciri (əsas), Nazirliyin CAEM modeli, OxLon (xarici kanallar), girdi-çıxdı (IO) və mikrosimulyasiya. İşarələr uyğundursa nəticə daha etibarlıdır; fərqlərin səbəbi hər sətirdə izah olunur.') + '<div id="c-body"></div>';
    var b = U.$('#c-body', v);
    U.need(['cmp'], b, function () {
      var N = U.T('N2_method_comparison'), ok = function (s) { return N.some(function (r) { return r.scenario === s.id; }); };
      var sc = U.cur(); if (!ok(U.scen(sc) || {})) sc = (U.scens().filter(ok)[0] || {}).id;
      var hz = U.HQ.get('h') || 'orta', R = N.filter(function (r) { return r.scenario === sc; }), H = R.filter(function (r) { return r.horizon === hz; });
      var bySc = U.by(N, 'scenario'), agg = Object.keys(bySc).map(function (k) { var L = bySc[k]; return { scenario_name: U.sname(k), n: L.length, agree: L.filter(function (r) { return r.sign_agree === true || r.sign_agree === 'True'; }).length / L.length, methods: U.uniq([].concat.apply([], L.map(function (r) { return U.ids(r.methods); }))).map(function (m) { return U.ENGS[m] || m; }).join(', ') }; });
      var all = N.filter(function (r) { return r.sign_agree === true || r.sign_agree === 'True'; }).length / (N.length || 1);
      b.innerHTML = '<div class="toolbar">' + U.scenSel('c-sc', sc, ok) + '</div>' + U.hztabs('muqayise', sc, hz) +
        '<div class="itiles"><div class="itile"><div class="l">Müqayisə sətirləri (bütün ssenarilər)</div><div class="v">' + U.nf(N.length, 0) + '</div><div class="s">göstərici × müddət × ssenari, ≥ 2 metod</div></div><div class="itile ' + (all >= 0.7 ? 'up' : 'down') + '"><div class="l">İşarələri uyğun olan pay</div><div class="v">' + U.pct(all, 0) + '</div><div class="s">bütün ssenarilər üzrə</div></div><div class="itile"><div class="l">Bu ssenaridə (' + hz + ')</div><div class="v">' + H.length + '</div><div class="s">göstərici; uyğun ' + H.filter(function (r) { return r.sign_agree === true || r.sign_agree === 'True'; }).length + '</div></div></div>' +
        '<div class="card pad"><h3>Metodlar yanaşı — ' + U.esc(U.sname(sc)) + ', ' + hz + ' müddət</h3><div id="c-ch" class="ch"></div><p class="small muted">Vahidlər göstərici adında; boş — həmin metodda bu kanal yoxdur.</p></div>' +
        U.dt('c-t', H, [{ k: 'label_az', l: 'Göstərici' }, { k: 'effect_unit', l: 'Vahid' }].concat(M.map(function (m) { return { k: m, l: U.ENGS[m], n: 1, d: 3 }; })).concat([{ k: 'spread', l: 'Fərq (max − min)', n: 1, d: 3 }, { k: 'sign_agree', l: 'İşarə uyğun', f: function (x) { return x === true || x === 'True' ? '<span class="chip acc">bəli</span>' : '<span class="chip bad">xeyr</span>'; } }, { k: 'caem_reliable', l: 'CAEM etibarlı', f: function (x) { return x === false || x === 'False' ? '<span class="chip bad">ETİBARSIZ</span>' : x == null ? '—' : 'bəli'; } }, { k: 'explanation_az', l: 'Fərqin izahı', full: 1, f: U.noteFmt }]), { title: 'Metodların müqayisəsi', file: 'metod_muqayisesi_' + sc }) +
        U.sec('Bütün ssenarilər', 'işarə uyğunluğu və istifadə olunan metodlar', U.dt('c-agg', agg, [{ k: 'scenario_name', l: 'Ssenari' }, { k: 'n', l: 'Sətir', n: 1 }, { k: 'agree', l: 'İşarə uyğun', p: 1 }, { k: 'methods', l: 'Metodlar' }], { title: 'NFR2 xülasəsi', bare: true }) + U.dt('c-all', N, null, { title: 'N2_method_comparison — tam cədvəl', file: 'N2_method_comparison', lim: 50 })) +
        U.sec('Nəticə diapazonu', 'əsas göstəricilər metodlar arası aşağı / yuxarı sərhəd kimi (P1_ranges)', U.dt('c-rg', U.T('P1_ranges').filter(function (r) { return r.scenario === sc && r.horizon === hz; }), [{ k: 'label_az', l: 'Göstərici' }, { k: 'effect_unit', l: 'Vahid' }, { k: 'low', l: 'Aşağı sərhəd', n: 1, d: 3 }, { k: 'low_method', l: 'Metod', f: function (x) { return U.ENGS[x] || x; } }, { k: 'high', l: 'Yuxarı sərhəd', n: 1, d: 3 }, { k: 'high_method', l: 'Metod', f: function (x) { return U.ENGS[x] || x; } }, { k: 'explanation_az', l: 'İzah', full: 1 }], { title: 'Diapazon', file: 'diapazon_' + sc })) +
        U.sec('Uzun müddət — kəsilməzlik yoxlaması', '2029 / 2030 / 2031 sapmaları; 2031 addımı limitdən kiçik olmalıdır (P1_longrun_continuity)', U.dt('c-ct', U.T('P1_longrun_continuity').filter(function (r) { return r.scenario === sc; }), [{ k: 'indicator', l: 'Göstərici' }, { k: 'v2029', l: '2029', n: 1, d: 3 }, { k: 'v2030', l: '2030', n: 1, d: 3 }, { k: 'v2031', l: '2031', n: 1, d: 3 }, { k: 'step_2030_31', l: 'Addım 2030→2031', n: 1, d: 3 }, { k: 'limit', l: 'Limit', n: 1, d: 3 }, { k: 'ok', l: 'Uyğun', f: function (x) { return x === true || x === 'True' ? '<span class="chip acc">bəli</span>' : '<span class="chip bad">xeyr</span>'; } }], { title: 'Kəsilməzlik', bare: true }));
      var K = H.filter(function (r) { return M.filter(function (m) { return U.isNum(r[m]); }).length >= 2; }).slice(0, 14);
      U.barH(U.$('#c-ch', b), K.map(function (r) { return r.label_az + ' (' + U.unitShort(r.effect_unit) + ')'; }), null, 'təsir', { sets: M.filter(function (m) { return K.some(function (r) { return U.isNum(r[m]); }); }).map(function (m) { return { name: U.ENG[m], v: K.map(function (r) { return r[m]; }), c: U.ENGC[m] }; }) });
      U.bindSel(b, 'c-sc', function (id) { location.hash = '#/muqayise?s=' + U.enc(id) + '&h=' + U.enc(hz); });
    });
  };
})();
