/* p_risk.js — Risklər və yan təsirlər (FR4): triggered side effects with severity 1–4, automatic side-effect scenarios
   (oil / manat −1σ, weaker transmission, alternative financing), RiskUnit risk profile with vs without the policy,
   mitigation proposals, global sensitivity (Sobol top-3) and uncertainty bands. */
(function () {
  'use strict';
  var U = window.U;
  var SUB = [['', 'Yan təsirlər'], ['ssenari', 'Yan təsir ssenariləri'], ['profil', 'Risk profili'], ['tedbir', 'Azaldıcı tədbirlər'], ['hessaslig', 'Həssaslıq və qeyri-müəyyənlik']];
  U.RISKURL = function () { return /^https?:/.test(location.protocol) ? 'http://127.0.0.1:8791/panel/index.html' : '../../RiskUnit/panel/index.html'; };
  U.sev = function (s, t) { return '<span class="sev s' + (s || 1) + '">' + U.esc(t || s) + '</span>'; };
  U.seCount = function (sc) { var m = (U.META.se || {})[sc]; if (!m) return ''; return '<a href="#/risk?s=' + U.enc(sc) + '">' + U.icon('warn', 13) + ' ' + m.n + ' yan təsir</a>' + (m.n3 ? ' · <b class="down">' + m.n3 + ' yüksək/kritik</b>' : '') + ' · ən yüksək ciddilik ' + U.sev(m.max, ['', 'aşağı', 'orta', 'yüksək', 'kritik'][m.max]); };
  function riskLinks(ids) { return U.ids(ids).map(function (r) { return '<a class="chip" href="' + U.RISKURL() + '#' + '/reyestr/' + U.esc(r) + '" target="_blank" rel="noopener" title="RiskUnit reyestri">' + U.esc(r) + '</a>'; }).join(' '); }
  function side(v, sc) {
    var S = U.T('P4_side_effects').filter(function (r) { return r.scenario === sc; }), B = S.filter(function (r) { return r.variant === 'base'; });
    if (!S.length) { v.insertAdjacentHTML('beforeend', '<div class="vmsg ok"><b>Bu ssenari üçün heç bir yan təsir qaydası tetiklənməyib.</b> Qaydalar kitabxanası: «Metodologiya» → konfiqurasiya.</div>'); return; }
    var fam = U.by(B, 'family');
    v.insertAdjacentHTML('beforeend', '<div class="expl">Yan təsirlər <b>qaydalar kitabxanası</b> (<code>config/side_effect_rules.csv</code>) ilə avtomatik aşkarlanır: hər qayda bir göstəricini (fiskal sürüşmə, inflyasiya, idxal sızması, qeyri-formallaşma, rent axtarışı, regional disbalans…) hədlərlə müqayisə edir və ciddilik verir: 1 aşağı, 2 orta, 3 yüksək, 4 kritik. Riskə klikləyin — RiskUnit reyestrində açılır.</div>' +
      '<div class="itiles">' + Object.keys(fam).map(function (f) { var mx = Math.max.apply(null, fam[f].map(function (r) { return r.severity; })); return '<div class="itile' + (mx >= 3 ? ' down' : '') + '"><div class="l">' + U.esc(f) + '</div><div class="v">' + fam[f].length + '</div><div class="s">ən yüksək: ' + U.sev(mx, ['', 'aşağı', 'orta', 'yüksək', 'kritik'][mx]) + '</div></div>'; }).join('') + '</div>' +
      '<div class="card"><div class="alist">' + B.slice().sort(function (a, b) { return b.severity - a.severity; }).map(function (r) { return '<div class="arow">' + U.sev(r.severity, r.severity_az) + '<div><b>' + U.esc(r.name_az) + '</b> <span class="muted small">· ' + U.esc(r.family) + ' · ' + U.esc(r.horizon || '') + (r.year ? ' ' + r.year : '') + (r.affected_group ? ' · ' + U.esc(r.affected_group) : '') + '</span><div class="small">' + U.esc(r.explanation_az) + '</div></div><span>' + riskLinks(r.risk_ids) + ' ' + U.tier(r.tier) + '</span></div>'; }).join('') + '</div></div>' +
      U.dt('r-se', S, [{ k: 'variant_name_az', l: 'Ssenari / şərt' }, { k: 'severity_az', l: 'Ciddilik', f: function (x, o) { return U.sev(o.severity, x); } }, { k: 'name_az', l: 'Yan təsir' }, { k: 'family', l: 'Ailə' }, { k: 'value', l: 'Kəmiyyət', n: 1 }, { k: 'unit', l: 'Vahid' }, { k: 'horizon', l: 'Müddət' }, { k: 'affected_group', l: 'Təsirlənən qrup' }, { k: 'risk_ids', l: 'Risklər' }, { k: 'change_vs_base', l: 'Əsasa nisbətən' }, { k: 'explanation_az', l: 'İzah' }], { title: 'Bütün yan təsirlər (əsas və şərtli ssenarilər)', file: 'yan_tesirler_' + sc }));
  }
  function variants(v, sc) {
    var R = U.T('P4_side_effect_scenarios').filter(function (r) { return r.scenario === sc; }), vs = U.uniq(R.map(function (r) { return r.variant_name_az; }));
    var K = ['gdp_real', 'cpi', 'unemp_rate', 'budget_balance_pct', 'debt_pct'].filter(function (k) { return R.some(function (r) { return r.indicator === k; }); }), hz = U.HQ.get('h') || 'orta';
    v.insertAdjacentHTML('beforeend', '<div class="expl">Hər siyasət <b>əlverişsiz şəraitdə</b> yenidən hesablanır: neft qiyməti −1σ, manat −1σ, zəif ötürmə (ən təsirli əmsallar −1 standart xəta), alternativ maliyyələşmə. Siyasət təsiri = (siyasət + şərt) − (yalnız şərt), eyni vintaj. «Dəyişmə» — əsas qiymətləndirmədən fərq.</div>' + U.hztabs('risk/ssenari', sc, hz) +
      '<div class="card pad"><div id="v-ch" class="ch"></div></div>' + U.dt('r-v', R, [{ k: 'variant_name_az', l: 'Şərt' }, { k: 'label_az', l: 'Göstərici' }, { k: 'horizon', l: 'Müddət' }, { k: 'effect_base', l: 'Əsas təsir', n: 1, d: 3 }, { k: 'effect_variant', l: 'Şərtlə təsir', n: 1, d: 3 }, { k: 'change', l: 'Dəyişmə', n: 1, d: 3 }, { k: 'effect_unit', l: 'Vahid' }], { title: 'Avtomatik yan təsir ssenariləri', file: 'yan_tesir_ssenarileri_' + sc }));
    var get = function (k, vn) { var r = R.filter(function (x) { return x.indicator === k && x.horizon === hz && x.variant_name_az === vn; })[0]; return r ? r.effect_variant : null; };
    var base = function (k) { var r = R.filter(function (x) { return x.indicator === k && x.horizon === hz; })[0]; return r ? r.effect_base : null; };
    U.barH(U.$('#v-ch', v), K.map(function (k) { var r = R.filter(function (x) { return x.indicator === k; })[0]; return r.label_az + ' (' + U.unitShort(r.effect_unit) + ')'; }), null, 'siyasət təsiri — ' + hz + ' müddət', { sets: [{ name: 'əsas', v: K.map(base), c: '#0E6F7C' }].concat(vs.map(function (vn, i) { return { name: vn, v: K.map(function (k) { return get(k, vn); }), c: ['#E07B00', '#6A3FB5', '#B3261E', '#1F6FB2', '#8A5300', '#455463'][i % 6] }; })) });
  }
  function profile(v, sc) {
    var R = U.T('P4_risk_profile').filter(function (r) { return r.scenario === sc; }), st = U.uniq(R.map(function (r) { return r.status; })).join(', ');
    var B = R.filter(function (r) { return r.variant === 'base'; }), K = U.uniq(B.map(function (r) { return r.indicator_az; }));
    v.insertAdjacentHTML('beforeend', '<div class="expl">RiskUnit (§15.5.3) paylanmaları <b>siyasətlə və siyasətsiz</b> HTTP API ilə hesablanır (status: ' + U.esc(st || '—') + '): həddin pozulma ehtimalı (məs. qeyri-neft artımı &lt; 2 %), gözlənilən itki ES10 (ən pis 10 %), P10 və median. <a href="' + U.RISKURL() + '" target="_blank" rel="noopener">Risk panelini aç →</a></div>' +
      '<div class="cols3">' + K.map(function (k, i) { return '<div class="card pad"><h3>' + U.esc(k) + '</h3><div id="rp-' + i + '" class="ch"></div></div>'; }).join('') + '</div>' +
      U.dt('r-p', R, [{ k: 'variant_name_az', l: 'Şərt' }, { k: 'indicator_az', l: 'Göstərici' }, { k: 'year', l: 'İl', n: 1 }, { k: 'threshold', l: 'Hədd' }, { k: 'P_without', l: 'Ehtimal: siyasətsiz', p: 1, d: 1 }, { k: 'P_with', l: 'Ehtimal: siyasətlə', p: 1, d: 1 }, { k: 'dP', l: 'Fərq, f.b.', f: function (x) { return U.isNum(x) ? U.sg(x * 100, 2) : '—'; }, n: 1 }, { k: 'ES10_without', l: 'ES10 siyasətsiz', n: 1, d: 2 }, { k: 'ES10_with', l: 'ES10 siyasətlə', n: 1, d: 2 }, { k: 'median_without', l: 'Median siyasətsiz', n: 1, d: 2 }, { k: 'median_with', l: 'Median siyasətlə', n: 1, d: 2 }, { k: 'esas_menbe', l: 'Əsas mənbə' }, { k: 'esas_menbe_izah', l: 'Mənbənin izahı' }, { k: 'P_with_ru', l: 'Siyasətlə (RiskUnit sürüşməsi)', p: 1, d: 1 }, { k: 'P_with_pu', l: 'Siyasətlə (PolicyUnit sürüşməsi)', p: 1, d: 1 }, { k: 'note_az', l: 'Qeyd' }, { k: 'status', l: 'Status' }], { title: 'Risk profili (RiskUnit)', note: U.MENBE, file: 'risk_profili_' + sc }));
    K.forEach(function (k, i) { var L = B.filter(function (r) { return r.indicator_az === k; }).sort(function (a, b) { return a.year - b.year; }); U.lines(U.$('#rp-' + i, v), [{ name: 'siyasətsiz', x: L.map(function (r) { return r.year; }), y: L.map(function (r) { return r.P_without * 100; }), c: '#E07B00', dash: 'dash', mode: 'lines+markers' }, { name: 'siyasətlə', x: L.map(function (r) { return r.year; }), y: L.map(function (r) { return r.P_with * 100; }), c: '#0E6F7C', mode: 'lines+markers' }], 'hədd pozulma ehtimalı, %', { years: true, h: 260 }); });
  }
  function mitig(v, sc) {
    var M = U.T('P4_mitigation').filter(function (r) { return r.scenario === sc; });
    v.insertAdjacentHTML('beforeend', '<div class="expl">Təkliflər üç mənbədən: qayda xəritəsi (<code>config/mitigation_map.csv</code>), siyasətə xas təkliflər (ardıcıllıq, hədəfləmə, kompensasiya, maliyyələşmə) və RiskUnit tədbirlər portfeli (T01–T30, optimallaşdırma). Hər təklifin məsul qurumu və izləmə göstəricisi var.</div>' +
      (M.length ? '<div class="card"><div class="alist">' + M.filter(function (r) { return r.proposal_az; }).slice(0, 12).map(function (r) { return '<div class="arow">' + U.prio(r.priority) + '<div><b>' + U.esc(r.proposal_type || r.family || '') + '</b> — ' + U.esc(r.proposal_az) + '<div class="small muted">' + U.esc(r.responsible_az || '') + (r.kpi_az ? ' · izləmə: ' + U.esc(r.kpi_az) : '') + '</div></div><span>' + riskLinks(r.risk_ids) + '</span></div>'; }).join('') + '</div></div>' : '') +
      U.dt('r-m', M, [{ k: 'priority', l: 'Prioritet', f: function (x) { return U.prio(x); } }, { k: 'source', l: 'Mənbə' }, { k: 'family', l: 'Ailə' }, { k: 'proposal_type', l: 'Növ' }, { k: 'proposal_az', l: 'Təklif' }, { k: 'measure_id', l: 'Tədbir' }, { k: 'measure_az', l: 'RiskUnit tədbiri' }, { k: 'responsible_az', l: 'Məsul' }, { k: 'cost_mln_azn', l: 'Xərc, mln AZN', n: 1 }, { k: 'kpi_az', l: 'İzləmə göstəricisi' }, { k: 'risk_ids', l: 'Risklər' }, { k: 'status', l: 'Status' }], { title: 'Azaldıcı tədbir təklifləri', file: 'tedbirler_' + sc }));
  }
  function sens(v, sc) {
    var S = U.T('P4_sensitivity').filter(function (r) { return r.scenario === sc; }), T3 = S.filter(function (r) { return r.top3 === true || r.top3 === 'True' || r.rank <= 3; });
    var outs = U.uniq(T3.map(function (r) { return r.outcome_label_az; })), Bd = U.T('P4_uncertainty_bands').filter(function (r) { return r.scenario === sc; }), bi = U.uniq(Bd.map(function (r) { return r.label_az; }));
    v.insertAdjacentHTML('beforeend', '<div class="expl"><b>Qlobal həssaslıq (Sobol)</b>: hər əsas nəticə üçün onun qeyri-müəyyənliyini ən çox izah edən 3 parametr (S1 — birbaşa pay, ST — qarşılıqlı təsirlərlə cəmi pay). <b>Qeyri-müəyyənlik zolağı</b> — parametr qeyri-müəyyənliyindən siyasət təsirinin 5–95 % intervalı (proqnoz zolağı deyil).</div>' +
      '<div class="cols2"><div class="card pad"><h3>Ən təsirli 3 sürücü (ST)</h3>' + U.sel('sn-o', outs.map(function (o) { return [o, o]; }), outs[0]) + '<div id="sn-ch" class="ch"></div></div><div class="card pad"><h3>Qeyri-müəyyənlik zolağı</h3>' + U.sel('ub-i', bi.map(function (o) { return [o, o]; }), bi[0]) + '<div id="ub-ch" class="ch"></div></div></div>' +
      U.dt('r-s', T3, [{ k: 'outcome_label_az', l: 'Nəticə' }, { k: 'rank', l: 'Rütbə', n: 1 }, { k: 'factor_label_az', l: 'Parametr' }, { k: 'S1', l: 'S1', n: 1, d: 3 }, { k: 'ST', l: 'ST', n: 1, d: 3 }, { k: 'ci_halfwidth', l: '± (95 %)', n: 1, d: 3 }, { k: 'converged', l: 'Yığıldı' }, { k: 'share_rejected', l: 'Qeyri-sabit pay', p: 1, d: 1 }, { k: 'N', l: 'N', n: 1 }, { k: 'method', l: 'Metod' }], { title: 'Sobol — ilk 3 sürücü', file: 'sobol_' + sc }) +
      U.dt('r-u', Bd, [{ k: 'label_az', l: 'Göstərici' }, { k: 'year', l: 'İl', n: 1 }, { k: 'horizon', l: 'Müddət' }, { k: 'central', l: 'Mərkəz', n: 1, d: 3 }, { k: 'p05', l: 'P5', n: 1, d: 3 }, { k: 'p50', l: 'Median', n: 1, d: 3 }, { k: 'p95', l: 'P95', n: 1, d: 3 }, { k: 'unit', l: 'Vahid' }, { k: 'method', l: 'Metod' }], { title: 'Qeyri-müəyyənlik zolaqları', file: 'zolaqlar_' + sc, lim: 60 }));
    var ds = function (o) { var L = T3.filter(function (r) { return r.outcome_label_az === o; }).sort(function (a, b) { return a.rank - b.rank; }); U.barH(U.$('#sn-ch', v), L.map(function (r) { return r.factor_label_az; }), null, 'Sobol indeksi', { sets: [{ name: 'ST', v: L.map(function (r) { return r.ST; }), c: '#0E6F7C' }, { name: 'S1', v: L.map(function (r) { return r.S1; }), c: '#9AC7CD' }] }); };
    var db = function (o) { var L = Bd.filter(function (r) { return r.label_az === o; }).sort(function (a, b) { return a.year - b.year; }), x = L.map(function (r) { return r.year; }); U.plot(U.$('#ub-ch', v), [].concat(U.band(x, L.map(function (r) { return r.p05; }), L.map(function (r) { return r.p95; }), '5–95 %', 0.16), U.band(x, L.map(function (r) { return r.p25; }), L.map(function (r) { return r.p75; }), '25–75 %', 0.28), [U.tr(x, L.map(function (r) { return r.central; }), 'mərkəzi təsir', '#0A5560', 'solid', 2.4, { mode: 'lines+markers' })]), U.layout((L[0] || {}).unit || '', { years: true, zero: true, h: 300 })); };
    if (outs.length) ds(outs[0]); if (bi.length) db(bi[0]);
    U.instab(v, sc);
    var a = U.$('#sn-o', v), b = U.$('#ub-i', v); if (a) a.onchange = function (e) { ds(e.target.value); }; if (b) b.onchange = function (e) { db(e.target.value); };
  }
  U.pages.risk = function (v, p) {
    var sub = p[1] || '';
    v.innerHTML = U.head('FR4 — risklər, yan təsirlər və risk modulu ilə inteqrasiya', 'Risklər və yan təsirlər', 'Siyasətin gözlənilməz nəticələri, əlverişsiz şəraitdə təsiri, RiskUnit risk profilinə təsiri və azaldıcı tədbirlər.') + '<div id="r-hd"></div>' + U.subtabs('risk', SUB, sub) + '<div id="r-body"></div>';
    var b = U.$('#r-body', v);
    U.need(['risk'], b, function () {
      var sc = U.cur(); if (U.HQ.get('s')) U.setCur(sc);
      U.$('#r-hd', v).innerHTML = '<div class="toolbar">' + U.scenSel('r-sc', sc, function (s) { return s.src === 'rəsmi'; }) + '<a class="btn sm ghost" href="' + U.RISKURL() + '" target="_blank" rel="noopener">Risk paneli (§15.5.3) →</a></div>';
      U.bindSel(v, 'r-sc', function (id) { U.HQ.set('s', id); location.hash = '#/risk' + (sub ? '/' + sub : '') + '?' + U.HQ.toString(); });
      if (!U.T('P4_side_effects').length && !U.T('P4_risk_profile').length) { b.innerHTML = U.empty('Yan təsirlər (FR4)'); return; }
      if (sub === 'ssenari') variants(b, sc); else if (sub === 'profil') profile(b, sc); else if (sub === 'tedbir') mitig(b, sc); else if (sub === 'hessaslig') sens(b, sc); else side(b, sc);
    });
  };
})();
