/* p_sec.js — Sektor təsirləri (FR2, girdi-çıxdı modeli), part 1: affected sectors with % change (output, value added,
   employment, prices; Ghosh), IO totals, multipliers (type I / II), linkages and key sectors (Rasmussen, extraction). */
(function () {
  'use strict';
  var U = window.U;
  U.SECN = function (code) { var r = U.T('cfg_io_sectors').filter(function (x) { return x.code === code; })[0]; return r ? r.name_az : code; };
  U.ioTab = function (stem, tab) { var L = U.T(stem), t = U.uniq(L.map(function (r) { return r.table; })); var cur = tab && t.indexOf(tab) >= 0 ? tab : t[t.length - 1]; return { rows: L.filter(function (r) { return r.table === cur; }), tables: t, cur: cur }; };
  U.secAffected = function (v, sc) {
    var A = U.T('P2_io_affected_sectors').filter(function (r) { return r.scenario === sc; });
    if (!A.length) { v.insertAdjacentHTML('beforeend', U.empty('Bu ssenari üçün IO sektor nəticəsi', 'Ssenarinin alətləri girdi-çıxdı modelinə ötürülmür (məs. minimum əmək haqqı, pensiya, uçot dərəcəsi). IO nümunə ssenarilərini və ya xərc / tarif / ixrac alətli ssenarini seçin.')); return; }
    var kinds = U.uniq(A.map(function (r) { return r.kind; })), k = U.HQ.get('k') || kinds[0], yr = A[0].year;
    var tot = U.T('P2_io_scenarios').filter(function (r) { return r.scenario === sc && r.group === 'ümumi'; });
    v.insertAdjacentHTML('beforeend', '<div class="expl">Girdi-çıxdı (IO) modeli siyasətin ilk ilində (' + yr + ') hansı sektorların nə qədər dəyişdiyini göstərir: <b>Leontief kəmiyyət modeli</b> — tələb artımının zəncir boyu ötürülməsi (aralıq alışlar), <b>qiymət modeli</b> — xərc artımının qiymətlərə ötürülməsi, <b>Ghosh</b> — təklif şokunun irəli ötürülməsi (şərhi məhduddur). Əmsallar sabitdir (2021 DSK cədvəli, 2025-ə GRAS ilə yenilənib); qiymət və davranış reaksiyaları yoxdur.</div>' +
      (tot.length ? '<div class="itiles">' + tot.map(function (r) { return '<div class="itile ' + (r.delta >= 0 ? 'up' : 'down') + '"><div class="l">' + U.esc(r.label_az) + '</div><div class="v">' + U.sg(r.delta, Math.abs(r.delta) >= 100 ? 0 : 1) + '</div><div class="s">' + U.esc(r.unit) + ' · ' + U.sg(r.delta_pct, 3) + ' % · ' + U.tier(r.tier) + '</div></div>'; }).join('') + '</div>' : '') +
      '<div class="toolbar">' + U.seg('s-kind', kinds.map(function (x) { return [x, x]; }), k) + '</div><div class="cols2"><div class="card pad"><h3>Ən çox təsirlənən sektorlar — ' + U.esc(k) + '</h3><div id="s-top" class="ch"></div></div><div>' +
      U.dt('s-aff', A.filter(function (r) { return r.kind === k; }), [{ k: 'rank', l: 'Rütbə', n: 1 }, { k: 'name_az', l: 'Sektor' }, { k: 'delta_pct', l: 'Dəyişmə, %', n: 1, d: 3 }, { k: 'delta', l: 'Dəyişmə', n: 1 }, { k: 'unit', l: 'Vahid' }, { k: 'method', l: 'Metod' }], { title: 'Təsirlənən sektorlar (FR2 qəbul formatı)', file: 'tesirlenen_sektorlar_' + sc, sort: ['rank', 1] }) + '</div></div>');
    var T = A.filter(function (r) { return r.kind === k; }).sort(function (a, b) { return Math.abs(b.delta_pct) - Math.abs(a.delta_pct); }).slice(0, 15);
    U.barH(U.$('#s-top', v), T.map(function (r) { return r.name_az; }), null, '% dəyişmə', { sets: [{ v: T.map(function (r) { return r.delta_pct; }), colors: T.map(function (r) { return r.delta_pct >= 0 ? (k === 'qiymət' ? '#B3261E' : '#1E7B4F') : (k === 'qiymət' ? '#1E7B4F' : '#B3261E'); }) }] });
    U.$('#s-kind', v).onclick = function (e) { var b = e.target.closest('[data-v]'); if (b) { U.HQ.set('k', b.getAttribute('data-v')); location.hash = '#/sektor?' + U.HQ.toString(); } };
  };
  U.secMult = function (v) {
    var t = U.ioTab('P2_io_multipliers', U.HQ.get('t')), R = t.rows.slice().sort(function (a, b) { return b.output_I - a.output_I; });
    v.insertAdjacentHTML('beforeend', '<div class="expl"><b>Multiplikator</b> — sektorun məhsuluna 1 manat əlavə son tələb bütün iqtisadiyyatda neçə manat buraxılış (əlavə dəyər, əmək ödənişi, idxal) yaradır. Tip I — yalnız aralıq alışlar; tip II — ev təsərrüfatlarının gəlirdən istehlakı da daxil. Məşğulluq — 1 mln AZN tələbə düşən iş yeri (nəfər).</div>' +
      '<div class="toolbar">' + U.seg('s-tab', t.tables.map(function (x) { return [x, x]; }), t.cur) + '</div><div class="cols2"><div class="card pad"><h3>Buraxılış multiplikatorları</h3><div id="s-mo" class="ch"></div></div><div class="card pad"><h3>Məşğulluq (nəfər / 1 mln AZN)</h3><div id="s-me" class="ch"></div></div></div>' +
      U.dt('s-mult', R, [{ k: 'name_az', l: 'Sektor' }, { k: 'output_I', l: 'Buraxılış I', n: 1, d: 3 }, { k: 'output_II', l: 'Buraxılış II', n: 1, d: 3 }, { k: 'va_I', l: 'ƏD I', n: 1, d: 3 }, { k: 'va_II', l: 'ƏD II', n: 1, d: 3 }, { k: 'comp_I', l: 'Əmək ödənişi I', n: 1, d: 3 }, { k: 'emp_I', l: 'Məşğulluq I', n: 1, d: 1 }, { k: 'emp_II', l: 'Məşğulluq II', n: 1, d: 1 }, { k: 'imp_I', l: 'İdxal I', n: 1, d: 3 }, { k: 'emp_typeI_mult', l: 'Məşğulluq mult.', n: 1, d: 2 }, { k: 'income_typeI_mult', l: 'Gəlir mult.', n: 1, d: 2 }, { k: 'rank_output_I', l: 'Rütbə', n: 1 }], { title: 'Multiplikatorlar — ' + t.cur, file: 'multiplikatorlar' }));
    U.barH(U.$('#s-mo', v), R.map(function (r) { return r.name_az; }), null, 'manat / 1 manat son tələb', { sets: [{ name: 'tip I', v: R.map(function (r) { return r.output_I; }), c: '#0E6F7C' }, { name: 'tip II', v: R.map(function (r) { return r.output_II; }), c: '#9AC7CD' }] });
    var E = t.rows.slice().sort(function (a, b) { return b.emp_I - a.emp_I; });
    U.barH(U.$('#s-me', v), E.map(function (r) { return r.name_az; }), E.map(function (r) { return r.emp_I; }), 'nəfər / 1 mln AZN (tip I)', { color: '#1F6FB2' });
    U.$('#s-tab', v).onclick = function (e) { var b = e.target.closest('[data-v]'); if (b) { U.HQ.set('t', b.getAttribute('data-v')); location.hash = '#/sektor/multiplikator?' + U.HQ.toString(); } };
  };
  U.secLink = function (v) {
    var t = U.ioTab('P2_io_linkages', U.HQ.get('t')), K = U.T('P2_io_key_sectors'), G = U.T('P2_io_ghosh_supply');
    v.insertAdjacentHTML('beforeend', '<div class="expl"><b>Geri əlaqə</b> — sektor başqa sektorlardan nə qədər alır (tələb çəkiciliyi); <b>irəli əlaqə</b> — onun məhsulu başqalarına nə qədər girdi olur. Hər ikisi > 1 olan sektorlar <b>açar sektor</b>dur: siyasət stimulunu iqtisadiyyata ən geniş yayır. Hipotetik çıxarma — sektor yoxa çıxsaydı ümumi buraxılış neçə % azalardı.</div>' +
      '<div class="toolbar">' + U.seg('s-tab', t.tables.map(function (x) { return [x, x]; }), t.cur) + '</div><div class="cols2"><div class="card pad"><h3>Geri və irəli əlaqə xəritəsi</h3><div id="s-sc" class="ch"></div><p class="small muted">Yuxarı sağ dörddəbir — açar sektorlar (hər iki indeks > 1).</p></div><div>' +
      U.dt('s-key', K, [{ k: 'name_az', l: 'Sektor' }, { k: 'key', l: 'Növ' }, { k: 'bl_index', l: 'Geri', n: 1, d: 3 }, { k: 'fl_index', l: 'İrəli', n: 1, d: 3 }, { k: 'extract_total_pct', l: 'Çıxarma itkisi, %', n: 1, d: 2 }, { k: 'rank_extraction', l: 'Rütbə', n: 1 }], { title: 'Sektorların əlaqə növü və açar sektorlar (' + ((K[0] || {}).table || '') + ')', file: 'acar_sektorlar' }) + '</div></div>' +
      U.dt('s-lnk', t.rows, null, { title: 'Əlaqə indeksləri və hipotetik çıxarma — ' + t.cur, file: 'elaqeler' }) +
      U.sec('Təklif şoku (Ghosh)', '−10 % təklif şokunun irəli ötürülməsi — məhdud şərh (qiymət reaksiyası yoxdur)', U.dt('s-gh', G.map(function (r) { return Object.assign({ shocked: U.SECN(r.shocked_sector), affected: U.SECN(r.sector) }, r); }), [{ k: 'shocked', l: 'Şoklanan sektor' }, { k: 'shock_pct', l: 'Şok, %', n: 1 }, { k: 'affected', l: 'Təsirlənən sektor' }, { k: 'dx_mln', l: 'Δ buraxılış, mln AZN', n: 1 }, { k: 'dx_pct', l: 'Δ buraxılış, %', n: 1, d: 3 }], { title: 'Ghosh təklif modeli', file: 'ghosh' })));
    var R = t.rows;
    U.scatter(U.$('#s-sc', v), R.map(function (r) { var key = r.bl_index > 1 && r.fl_index > 1; return { x: r.bl_index, y: r.fl_index, t: r.sector, c: key ? '#B3261E' : '#0E6F7C', s: 11, h: r.name_az + '<br>geri ' + U.nf(r.bl_index, 3) + ' · irəli ' + U.nf(r.fl_index, 3) }; }), 'geri əlaqə indeksi', 'irəli əlaqə indeksi', { h: 380, extra: [{ type: 'scatter', mode: 'lines', x: [1, 1], y: [0.5, 2.5], line: { color: '#9AA6B2', dash: 'dot', width: 1 }, hoverinfo: 'skip', showlegend: false }, { type: 'scatter', mode: 'lines', x: [0.6, 1.5], y: [1, 1], line: { color: '#9AA6B2', dash: 'dot', width: 1 }, hoverinfo: 'skip', showlegend: false }] });
    U.$('#s-tab', v).onclick = function (e) { var b = e.target.closest('[data-v]'); if (b) { U.HQ.set('t', b.getAttribute('data-v')); location.hash = '#/sektor/elaqe?' + U.HQ.toString(); } };
  };
})();
