#!/usr/bin/env python3
"""build_panel.py — v2 data bundles of the Mikro Model İş paneli, from MicroUnit/output (stable indicator ids).

    python3 panel/build_panel.py                 # from MicroUnit/
    python3 panel/build_panel.py --db PATH       # saved scenarios from another API database (default api/micro.db)

Writes panel/data/*.js:
  fr1.js … fr12.js   every catalog component (FRx_indicator_catalog.csv + FRx_forecast_tidy.csv): history, 2026–2030
                     for every scenario, growth, 5–95 % band, imputed points (FR12_series_filled.csv), equation ids
  eqidx.js, eq_frX.js equation registries (index + full regression output, loaded on demand), sens.js tornado data
  synthetic.js, synecon.js  FR10/FR12 Layer B (demonstration + full firm-level econometrics)
  inputs.js, saved.js scenario-builder inputs (engines) and saved custom scenarios; meta.js texts and lists
  ../py/microunit_bundle.zip, ../py/bundle.js  in-browser Python backend (Pyodide; _build/pybundle.py, --no-pybundle skips)
and MicroUnit/index.html (hub), panel/coverage_report.csv, panel/i18n/untranslated.txt.

Checks (exit 1 on failure): completeness — every catalog component × scenario × 2026–2030 has a value;
links — catalog equation ids exist, local hrefs and bundle files exist, every #/route has a page;
translation — no English prose in bundles, JS strings, index.html or the hub (panel/i18n/az.csv translates).
Output is deterministic (sorted keys, fixed rounding); set SOURCE_DATE_EPOCH to pin the date stamp.
"""
import argparse
import re
import sys
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _build import pcore as C, p_tidy, p_eq, p_i18n, p_synth, p_synecon, p_inputs, p_meta, p_hub, pybundle   # noqa: E402

SKIP = {"i", "id", "f", "k", "src", "eq", "comp", "n", "c", "r", "egt", "_allow", "eq_id", "rule_key", "part", "model_id",
        "model", "term", "dependent", "regressors", "section", "parameter", "sample", "ratio_type", "options",
        "overrides", "series", "warn", "file", "slug", "kpi", "scen", "alt", "md5", "date", "mode", "lb", "source",
        "tied_with", "name", "author", "updated", "created", "type", "kind", "unit", "status", "st", "dep", "value", "default"}


def write_series(data, out, tr):
    for m, recs in out.items():
        for r in recs:
            for k in ("g", "e", "u"):
                r[k] = tr(r.get(k))
        js = p_i18n.to_json(recs)
        (data / f"{m.lower()}.js").write_text("/* generated by build_panel.py from MicroUnit/output — do not edit */\n"
                                              "window.MICRO=window.MICRO||{S:[]};window.MICRO.S=window.MICRO.S.concat(" + js + ");\n",
                                              encoding="utf-8")


def check_links(out, idx):
    errs = []
    eqids = {e["id"] for e in idx}
    for m, recs in out.items():
        for r in recs:
            for e in r.get("eq", []):
                if e not in eqids:
                    errs.append(f"{r['i']}: tənlik reyestrdə yoxdur: {e}")
    html = (C.PANEL / "index.html").read_text(encoding="utf-8")
    for src in re.findall(r'(?:src|href)="([^"#?]+)"', html):
        if not src.startswith(("http", "data:")) and not (C.PANEL / src).exists():
            errs.append(f"index.html: fayl yoxdur: {src}")
    js = {p.name: p.read_text(encoding="utf-8") for p in sorted((C.PANEL / "js").glob("*.js"))}
    pages = set()
    for t in js.values():
        pages |= set(re.findall(r"U\.pages\[?\.?'?\"?([\w]*)'?\"?\]?\s*=\s*function", t))
        pages |= set(re.findall(r"U\.pages\.(\w+)\s*=", t))
    pages |= {f["slug"] for f in p_meta.FRS} | {""}
    for name, t in js.items():
        for r in re.findall(r"#/([a-z0-9]*)", t):
            if r not in pages:
                errs.append(f"{name}: '#/{r}' marşrutu üçün səhifə yoxdur")
        for rel in re.findall(r"'\.\./(site/[^'#?]+|output/)", t):
            if not (C.UNIT / rel).exists():
                errs.append(f"{name}: keçid yoxdur: ../{rel}")
    hub = (C.UNIT / "index.html").read_text(encoding="utf-8")
    for href in re.findall(r'href="([^"#?]+)', hub):
        if not href.startswith(("http", "data:")) and not (C.UNIT / href).exists():
            errs.append(f"index.html (mərkəz): keçid yoxdur: {href}")
    return errs


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=None, help="saxlanmış ssenarilər üçün SQLite (standart: api/micro.db)")
    ap.add_argument("--no-pybundle", action="store_true", help="brauzer üçün Python paketini (panel/py/) yeniləmə")
    a = ap.parse_args()
    data = C.PANEL / "data"
    data.mkdir(parents=True, exist_ok=True)
    tr = p_i18n.Tr()
    out, groups, cov, cerr = p_tidy.build()
    groups = {m: [tr(g) for g in gs] for m, gs in groups.items()}
    write_series(data, out, tr)
    C.pd.DataFrame(cov).to_csv(C.PANEL / "coverage_report.csv", index=False)
    idx, hdr, eqscan = p_eq.build(data, tr)
    syn = p_synth.build(data, tr)
    syne = p_synecon.build(data, tr, hdr)
    inp, ierr, saved = p_inputs.build(data, tr, a.db)
    ids = {r["i"] for recs in out.values() for r in recs}
    meta = p_meta.build(data, ids, groups, tr, extra={"hdr": hdr})
    stats = {"series": len(ids), "paths": sum(len(r.get("s", {})) for recs in out.values() for r in recs),
             "eqs": len(idx), "bands": sum("q" in r for recs in out.values() for r in recs)}
    hub = p_hub.build(stats, meta)
    for m, recs in out.items():
        print(f"{m:5s} {len(recs):4d} komponent · {sum(1 for e in idx if e['f'] == m):3d} tənlik")
    print(f"göstərici {stats['series']}, ssenari sırası {stats['paths']} (× 5 il), zolaq {stats['bands']}, tənlik {stats['eqs']}, "
          f"saxlanmış ssenari {len(saved)}, mühərrik girişləri {len(inp)}/6{' (' + '; '.join(ierr) + ')' if ierr else ''}")
    bad = []
    objs = [(f"{m.lower()}.js", recs) for m, recs in out.items()] + eqscan + [("synthetic.js", syn), ("synecon.js", syne),
                                                                              ("inputs.js", inp), ("meta.js", meta)]
    for name, o in objs:
        p_i18n.scan(o, name, SKIP, out=bad)
    bad += p_i18n.scan_js(sorted((C.PANEL / "js").glob("*.js")))
    bad += p_i18n.scan_html(C.PANEL / "index.html") + p_i18n.scan_html(hub)
    p_i18n.dump_report(bad, C.PANEL / "i18n" / "untranslated.txt")
    if not a.no_pybundle:                                  # in-browser backend: panel/py/microunit_bundle.zip + bundle.js
        print(pybundle.report(pybundle.build(C.PANEL, "micro_web")))
    lerr = check_links(out, idx)
    ok = True
    print("tamlıq:", C.pd.DataFrame(cov).status.value_counts().to_dict())
    if cerr:
        ok = False
        print(f"TAMLIQ YOXLAMASI UĞURSUZ: {len(cerr)}")
        for e in cerr[:40]:
            print("  -", e)
    else:
        print("TAMLIQ OK — hər kataloq komponenti hər ssenaridə 2026–2030 illərinin hamısını daşıyır")
    if lerr:
        ok = False
        print(f"KEÇİD YOXLAMASI UĞURSUZ: {len(lerr)}")
        for e in lerr[:40]:
            print("  -", e)
    else:
        print("KEÇİDLƏR OK — tənlik id-ləri, fayllar və marşrutlar mövcuddur")
    if bad:
        ok = False
        print(f"TƏRCÜMƏ YOXLAMASI UĞURSUZ: {len(bad)} sətir (panel/i18n/untranslated.txt):")
        for b in bad[:40]:
            print("  -", " | ".join(b))
    else:
        print("TƏRCÜMƏ OK — paketlərdə, JS-də və HTML-də tərcümə olunmamış ingiliscə mətn tapılmadı")
    print("möhür", meta["stamp"]["md5"], meta["stamp"]["date"])
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
