"""pinfo.py — explanatory texts for the drawer (definition, model, drivers, limitations). Prose only, no numbers."""
I = {
    "FR1.model": dict(d="AZSEM-FR1 struktur sisteminin dəyişəni — modelin öz kodu ilə, eyni vaxtda həll olunan sistemin çıxışı.",
                      m="Blok-rekursiv struktur sistem; hər sektor öz sürücüsü ilə, sistem milli hesablar, fiskal, monetar və "
                        "tədiyə balansı eynilikləri ilə qapanır. Səviyyə əlaqələri DOLS ilə.",
                      r="Neftin qiyməti və hasilatı (ssenari), dövlət investisiyası, xarici tələb, əhali, faiz siyasəti.",
                      l=["Sabit artım etalonuna qarşı model təxminən bərabərdir.", "Kointeqrasiya əksər əlaqələrdə təsdiqlənmir.",
                         "Bəzi sektorlarda artımın çoxu deterministik trenddir."]),
    "FR1.accounts": dict(d="Sektor və bazar hesabı: real həcm (2015 qiymətləri), deflyator və nominal dəyər. «Real» = nominal / deflyator.",
                         m="AZSEM-FR1 sisteminin həllindən; hər sektor ayrıca tənlik, birlikdə vahid sistem.",
                         r="FR1 ssenari fərziyyələri (Əsas / Mənfi / İslahat).",
                         l=["İş kitabında giriş-çıxış cədvəli yoxdur; sektorlararası əlaqələr qiymətləndirilir.",
                            "Emal, tikinti və nəqliyyat proqnozları ən zəifdir.",
                            "Sektor investisiya deflyatorları nəşr olunmur."]),
    "FR1.contrib": dict(d="Sektorun real ÜDM artımına töhfəsi, faiz bəndi (Əsas ssenari).", m="Real əlavə dəyər artımı × əvvəlki ilin payı.",
                        r="FR1 sektor tənlikləri.", l=["Modul yalnız Əsas ssenari üçün parçalanma ixrac edir."]),
    "FR3.wage": dict(d="Orta aylıq nominal və real əmək haqqı; dövlət/qeyri-dövlət və neft/qeyri-neft bölgüləri eyni milli ortaya uzlaşdırılır.",
                     m="DOLS tənlikləri (nominal homogenlik tətbiq olunub), 2026 cari qiymətləndirmə, iki bölgünün birgə uzlaşdırılması.",
                     r="FR1: məhsuldarlıq, qiymətlər; minimum əmək haqqı; neft mükafatı rıçağı.",
                     l=["Sabit artım etalonuna qarşı hold-out zəifdir.", "Neft sektoru tənliklə deyil, mükafat rıçağı ilə verilir.",
                        "Sektorlar və büdcə/qeyri-büdcə üzrə orta əmək haqqı mənbələrdə yoxdur."]),
    "FR3.model": dict(d="FR3 modelinin bütün ixrac olunan dəyişənləri (uzlaşdırmadan əvvəl/sonra, əmsallar, minimum əmək haqqı və s.).",
                      m="AZWAGE-FR3.", r="FR1 makro yolları.", l=["Texniki sıralar: uzlaşdırma əmsalları və fərqlər."]),
    "FR3.branch": dict(d="Sənaye sahələri üzrə orta aylıq əmək haqqı (sənaye paneli).", m="Sahə əmək haqqı FR3 yolu ilə.",
                       r="FR3 orta əmək haqqı.", l=["Məlumat xarakterlidir; FR10 sahə səviyyələri üçün işlətmir."]),
    "FR3.sectemp": dict(d="Sektorlar üzrə muzdlu işçilərin sayı (FR3-ün əmək haqqı fondu üçün).", m="Sabit tərkib.",
                        r="FR1 məşğulluğu.", l=["Tərkib 2026-dan sonra sabit saxlanılır."]),
    "FR4.activity": dict(d="İqtisadi fəaliyyət növləri üzrə məşğul əhali və muzdlu işçilər, min nəfər.",
                         m="Pay sistemi (paylar müsbət, cəmi bir): sabit paylarla birləşdirilmiş buraxılış elastikliyinin bərabər çəkili kombinasiyası.",
                         r="FR1: ümumi məşğulluq, sektor buraxılışı.",
                         l=["Fəaliyyət növləri səviyyəsində dəqiqlik məhduddur.", "Sektor tərkibi iqtisadiyyata zəif reaksiya verir."]),
    "FR4.group": dict(d="Səkkiz fəaliyyət qrupu üzrə məşğul əhali (Əsas ssenari, zolaqla).", m="FR4 pay sistemi.",
                      r="FR1.", l=["Modul qruplar üçün yalnız Əsas ssenari yolunu zolaqla ixrac edir; ssenarilər fəaliyyət növlərindədir."]),
    "FR4.inst": dict(d="Dövlət/qeyri-dövlət, büdcə/qeyri-büdcə, neft/qeyri-neft bölgüləri.",
                     m="Ayrı bloklar; dövlət payı və muzdlu işçi payı verilmiş yoldur, neft məşğulluğu neft hasilatına bağlıdır.",
                     r="FR1 hasilat yolları; FR3.", l=["Dövlət payı proqnoz deyil, fərziyyədir.", "Neft məşğulluğu on müşahidəyə əsaslanır."]),
    "FR5.total": dict(d="Əhaliyə göstərilən pullu xidmətlər: real həcm (2015 qiymətləri), nominal dəyər, deflyator.",
                      m="Aqreqat tələb tənliyi: adambaşına real həcm ~ adambaşına real gəlir + nisbi qiymət (DOLS).",
                      r="FR1: real gəlir, əhali, xidmət deflyatoru.",
                      l=["Test pəncərəsində təsadüfi gəzişməni üstələmir.", "Zolaqlar az sayda tarixi yola əsaslanır."]),
    "FR5.type": dict(d="On üç xidmət növü: həcm, dəyər, deflyator və pay.", m="Multinomial-logit pay sistemi, Engel əmsalları büzülmə ilə.",
                     r="FR5 aqreqatı, FR1 gəliri.", l=["Növlər üzrə sıralama zəif dəstəklənir.", "Növ nisbi qiymətləri sabit saxlanılır."]),
    "FR5.split": dict(d="Hüquqi şəxs / fərdi sahibkar və dövlət / qeyri-dövlət bölgüləri.", m="Pay qaydası (qərar qaydası ilə seçilmiş).",
                      r="FR5 aqreqatı.", l=["Paylar Əsas ssenaridə sabitdir."]),
    "FR10.branch": dict(d="Sənaye sahəsi (NACE 2 rəqəm): buraxılış, pay, işçilər, məhsuldarlıq, əmək haqqı, marja.",
                        m="Neft emalı — güc və neftin qiyməti; qalan emal sahələri — əlaqəli sektor modeli ilə sabit payların kombinasiyası.",
                        r="FR1 sektor əlavə dəyəri və deflyatorları; FR4 işçilər; FR3/FR1 əmək haqqı.",
                        l=["Real sahə məhsulu sabit artımdan pisdir; nominal daha etibarlıdır.", "Marja yuxarı hədd göstəricisidir."]),
    "FR10.section": dict(d="Sənaye bölmələri (B, C, D, E): buraxılış, əlavə dəyər, mənfəət və əməyin payı.",
                         m="Bölmə buraxılışı = 2025 × FR1 nominal əlavə dəyər indeksi.", r="FR1.", l=["Maliyyə vəziyyəti aqreqat səviyyədədir."]),
    "FR10.region": dict(d="14 iqtisadi region üzrə sənaye buraxılışı və pay.", m="Multinomial-logit pay sistemi (neft-sektor tərkibi).",
                        r="FR1 mədənçıxarma/emal əlavə dəyəri.", l=["Bakının payı dominantdır."]),
    "FR10.hhi": dict(d="Emal sənayesi sahələri arasında Herfindahl–Hirschman indeksi (müəssisə səviyyəsində deyil).",
                     m="Sahə paylarından.", r="Sahə proqnozları.", l=["Müəssisə HHI-si B qatında, real məlumatla."]),
    "FR10.own": dict(d="Qeyri-dövlət sektorunun sənaye buraxılışında payı.", m="Tərkib eyniliyi.", r="Sahə proqnozları.", l=[]),
    "FR10.product": dict(d="Məhsulların natural ifadədə proqnozu (adlar çıxış faylından, ingiliscə).",
                         m="Sahə real buraxılışı × 2023–25 intensivliyi.", r="FR10 sahə proqnozu.", l=["Törəmə proqnozdur, ayrıca tənlik yoxdur."]),
    "FR12.activity": dict(d="DSK fəaliyyət qrupları üzrə qeydiyyat: yeni qeydiyyatlar, ləğv edilənlər, say, giriş və çıxış əmsalları.",
                          m="Doğumlar — vahid effektli loq modeli; say eyniliyi N(t)=(N(t−1)+B)/(1+x); qayda kəsimdən əvvəl seçilir.",
                          r="FR1 tələb sürücüsü.", l=["Hər qrup üzrə beş illik müşahidə.", "Qeydiyyat bazara girişlə eyni deyil."]),
    "FR12.region": dict(d="14 iqtisadi region üzrə statistik vahidlər: giriş, çıxış, say.", m="Eyni qayda, regional sürücülərlə.",
                        r="FR10 regional buraxılış, kredit faizi.", l=["Regional çıxış qaydası təsadüfi gəzişməni üstələmir."]),
    "FR12.conc": dict(d="Ölçü qruplarına əsaslanan konsentrasiya hədləri (HHI, CR4) və KOS payı.",
                      m="Aşağı/yuxarı hədlər — ölçülmüş deyil, sərhədlənmiş.", r="KOS payı modeli.",
                      l=["Fəaliyyət qrupları antiinhisar bazarlarından genişdir."]),
}
